"""Deterministic release adapter for bounded engineering documentation."""

import ast
import json
import re

from fam_os.core.engineering import (
    DocumentationArtifactKind, DocumentationGenerationRequest,
    DocumentationSourceContent, SignedDocumentationRecipe,
)


_GENERATOR_ID = "fam.documentation.deterministic.v1"


class DeterministicDocumentationGenerator:
    def generate(
        self, recipe: SignedDocumentationRecipe,
        request: DocumentationGenerationRequest,
        sources: tuple[DocumentationSourceContent, ...],
    ) -> bytes:
        if recipe.generator_id != _GENERATOR_ID:
            raise LookupError("documentation generator adapter is unavailable")
        renderers = {
            DocumentationArtifactKind.DIAGRAM: _diagram,
            DocumentationArtifactKind.API_REFERENCE: _api_reference,
            DocumentationArtifactKind.RUNBOOK: _runbook,
            DocumentationArtifactKind.CHANGELOG: _changelog,
            DocumentationArtifactKind.GENERATED_CODE: _generated_code,
        }
        value = renderers[request.kind](request, sources, recipe.coordinate)
        return (value.rstrip() + "\n").encode("utf-8")


def _header(title, request, coordinate) -> list[str]:
    return [
        f"# {title}", "", "<!-- Generated by FAM_OS; do not edit directly. -->",
        f"<!-- task: {request.task_id}; recipe: {coordinate} -->", "",
    ]


def _diagram(request, sources, coordinate) -> str:
    lines = [
        "%% Generated by FAM_OS; do not edit directly.",
        f"%% task: {request.task_id}; recipe: {coordinate}",
        "flowchart LR",
        f'  OUTPUT["{_label(request.output_path)}"]',
    ]
    for index, item in enumerate(sources):
        lines.append(f'  SOURCE{index}["{_label(item.source.path)}"] --> OUTPUT')
    return "\n".join(lines)


def _api_reference(request, sources, coordinate) -> str:
    lines = _header("Generated API reference", request, coordinate)
    for item in sources:
        lines.extend((f"## `{item.source.path}`", ""))
        symbols = _public_symbols(item.source.path, item.content)
        lines.extend(
            (f"- `{kind} {name}`" for kind, name in symbols)
            if symbols else ("- No public symbols were detected.",)
        )
        lines.append("")
    return "\n".join(lines)


def _runbook(request, sources, coordinate) -> str:
    lines = _header("Generated runbook", request, coordinate)
    lines.extend((
        "## Scope", "",
        "This runbook is bound to the source snapshot listed below.", "",
        "## Verification", "",
        "Regenerate this artifact through the owning FAM_OS engineering task, then run the task's signed verification recipes.",
        "", "## Source snapshot", "",
    ))
    lines.extend(_source_rows(sources))
    return "\n".join(lines)


def _changelog(request, sources, coordinate) -> str:
    lines = _header("Generated changelog", request, coordinate)
    lines.extend(("## Candidate source snapshot", ""))
    lines.extend(_source_rows(sources))
    return "\n".join(lines)


def _generated_code(request, sources, coordinate) -> str:
    values = {
        item.source.path: item.source.content_sha256 for item in sources
    }
    payload = json.dumps(values, sort_keys=True, indent=4)
    return "\n".join((
        '"""Generated source manifest; regenerate through FAM_OS."""', "",
        f"GENERATOR_RECIPE = {coordinate!r}",
        f"SOURCE_DIGESTS = {payload}",
    ))


def _source_rows(sources) -> list[str]:
    return [
        f"- `{item.source.path}` — `{item.source.content_sha256}`"
        for item in sources
    ]


def _public_symbols(path: str, content: bytes) -> tuple[tuple[str, str], ...]:
    text = content.decode("utf-8", "strict")
    if path.endswith(".py"):
        try:
            tree = ast.parse(text)
        except SyntaxError:
            return ()
        return tuple(
            ("class" if isinstance(item, ast.ClassDef) else "function", item.name)
            for item in tree.body
            if isinstance(item, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
            and not item.name.startswith("_")
        )
    pattern = re.compile(
        r"^(?:export\s+)?(?:class|interface|function|const|type)\s+([A-Za-z_$][\w$]*)",
        re.MULTILINE,
    )
    return tuple(("symbol", name) for name in pattern.findall(text))


def _label(value: str) -> str:
    return value.replace("\\", "/").replace('"', "'").replace("[", "(").replace("]", ")")[:160]
