"""Unprivileged local FAM Shell contracts and controller."""

from fam_os.shell.contracts import (
    SHELL_CONTRACT_VERSION,
    SHELL_SNAPSHOT_CONTRACT_VERSION,
    ShellApprovalRequest,
    ShellAskCommand,
    ShellVerifiedAskCommand,
    ShellCancelCommand,
    ShellContext,
    ShellContextKind,
    ShellDecision,
    ShellDecisionCommand,
    ShellPlanStep,
    ShellResult,
    ShellRunState,
    ShellSessionSnapshot,
    ShellSnapshotQuery,
    ShellStepState,
)
from fam_os.shell.legacy_snapshot import (
    LEGACY_SHELL_SNAPSHOT_VERSION,
    ShellResult as ShellResultV1Alpha1,
    ShellSessionSnapshot as ShellSessionSnapshotV1Alpha1,
    migrate_shell_snapshot_v1alpha1,
)
from fam_os.shell.controller import ShellController
from fam_os.shell.memory_contracts import (
    MAX_SHELL_MEMORY_PAGE,
    SHELL_MEMORY_CONTRACT_VERSION,
    ShellMemoryOperation,
    ShellMemoryQuery,
    ShellMemoryResponse,
)
from fam_os.shell.memory_render import render_memory_response
from fam_os.shell.adaptation_contracts import (
    MAX_SHELL_ADAPTATION_PAGE,
    SHELL_ADAPTATION_CONTRACT_VERSION,
    ShellAdaptationOperation,
    ShellAdaptationQuery,
    ShellAdaptationResponse,
)
from fam_os.shell.adaptation_render import render_adaptation_response
from fam_os.shell.peer_contracts import (
    MAX_SHELL_PEER_PAGE,
    SHELL_PEER_CONTRACT_VERSION,
    ShellPeerOperation,
    ShellPeerProbeRequest,
    ShellPeerQuery,
    ShellPeerResponse,
)
from fam_os.shell.peer_render import render_peer_response
from fam_os.shell.engineering_authority_contracts import (
    SHELL_ENGINEERING_AUTHORITY_VERSION,
    ShellEngineeringActivationRequest,
    ShellEngineeringAuthorityOperation,
    ShellEngineeringAuthorityResponse,
    ShellEngineeringContextRequest,
    ShellEngineeringGrantQuery,
    ShellEngineeringRevocationRequest,
)
from fam_os.shell.integration_environment_contracts import (
    SHELL_INTEGRATION_ENVIRONMENT_VERSION,
    ShellIntegrationEnvironmentControlRequest,
    ShellIntegrationEnvironmentOperation,
    ShellIntegrationEnvironmentQuery,
    ShellIntegrationEnvironmentRecord,
    ShellIntegrationStartIntentRecord,
    ShellIntegrationEnvironmentResponse,
    ShellIntegrationEnvironmentStartRequest,
)
from fam_os.shell.engineering_secret_contracts import (
    SHELL_ENGINEERING_SECRET_VERSION,
    ShellEngineeringSecretAuditEvent, ShellEngineeringSecretMetadata,
    ShellEngineeringSecretMutation, ShellEngineeringSecretOperation,
    ShellEngineeringSecretQuery, ShellEngineeringSecretResponse,
)
from fam_os.shell.engineering_candidate_contracts import (
    ShellEngineeringCandidateEditRequest,
    ShellEngineeringCandidateVerificationRequest,
    ShellEngineeringCandidateReverificationRequest,
    ShellEngineeringChangesetApplyRequest,
    ShellEngineeringChangesetPreviewRequest,
    ShellEngineeringIncidentAdvanceRequest,
    ShellEngineeringPublicationRequest,
)
from fam_os.shell.engineering_loop_contracts import (
    SHELL_ENGINEERING_LOOP_VERSION,
    ShellEngineeringLoopMutation,
    ShellEngineeringLoopOperation,
    ShellEngineeringLoopQuery,
    ShellEngineeringLoopResponse,
    ShellEngineeringLoopStartRequest,
    ShellEngineeringLoopView,
)
from fam_os.shell.ports import (
    ShellAdaptationGateway,
    ShellCoreClient,
    ShellCoreGateway,
    ShellMemoryGateway,
    ShellPeerGateway,
)
from fam_os.shell.render import render_contexts, render_snapshot
from fam_os.shell.engineering_projection import render_engineering_result
from fam_os.shell.terminal import TerminalShell, run_terminal

__all__ = [
    "SHELL_CONTRACT_VERSION",
    "SHELL_SNAPSHOT_CONTRACT_VERSION",
    "LEGACY_SHELL_SNAPSHOT_VERSION",
    "ShellApprovalRequest",
    "ShellAskCommand",
    "ShellVerifiedAskCommand",
    "ShellCancelCommand",
    "ShellContext",
    "ShellContextKind",
    "ShellController",
    "ShellCoreClient",
    "ShellCoreGateway",
    "ShellMemoryGateway",
    "ShellAdaptationGateway",
    "ShellPeerGateway",
    "ShellDecision",
    "ShellDecisionCommand",
    "ShellPlanStep",
    "ShellResult",
    "ShellRunState",
    "ShellSessionSnapshot",
    "ShellResultV1Alpha1",
    "ShellSessionSnapshotV1Alpha1",
    "migrate_shell_snapshot_v1alpha1",
    "ShellSnapshotQuery",
    "ShellStepState",
    "MAX_SHELL_MEMORY_PAGE",
    "SHELL_MEMORY_CONTRACT_VERSION",
    "ShellMemoryOperation",
    "ShellMemoryQuery",
    "ShellMemoryResponse",
    "MAX_SHELL_ADAPTATION_PAGE",
    "SHELL_ADAPTATION_CONTRACT_VERSION",
    "ShellAdaptationOperation",
    "ShellAdaptationQuery",
    "ShellAdaptationResponse",
    "MAX_SHELL_PEER_PAGE",
    "SHELL_PEER_CONTRACT_VERSION",
    "ShellPeerOperation",
    "ShellPeerProbeRequest",
    "ShellPeerQuery",
    "ShellPeerResponse",
    "SHELL_ENGINEERING_AUTHORITY_VERSION",
    "ShellEngineeringActivationRequest",
    "ShellEngineeringAuthorityOperation",
    "ShellEngineeringAuthorityResponse",
    "ShellEngineeringContextRequest",
    "ShellEngineeringGrantQuery",
    "ShellEngineeringRevocationRequest",
    "SHELL_INTEGRATION_ENVIRONMENT_VERSION",
    "ShellIntegrationEnvironmentControlRequest",
    "ShellIntegrationEnvironmentOperation",
    "ShellIntegrationEnvironmentQuery",
    "ShellIntegrationEnvironmentRecord",
    "ShellIntegrationStartIntentRecord",
    "ShellIntegrationEnvironmentResponse",
    "ShellIntegrationEnvironmentStartRequest",
    "SHELL_ENGINEERING_SECRET_VERSION",
    "ShellEngineeringSecretAuditEvent",
    "ShellEngineeringSecretMetadata",
    "ShellEngineeringSecretMutation",
    "ShellEngineeringSecretOperation",
    "ShellEngineeringSecretQuery",
    "ShellEngineeringSecretResponse",
    "SHELL_ENGINEERING_LOOP_VERSION",
    "ShellEngineeringLoopMutation",
    "ShellEngineeringLoopOperation",
    "ShellEngineeringLoopQuery",
    "ShellEngineeringLoopResponse",
    "ShellEngineeringLoopStartRequest",
    "ShellEngineeringLoopView",
    "ShellEngineeringCandidateEditRequest",
    "ShellEngineeringCandidateVerificationRequest",
    "ShellEngineeringCandidateReverificationRequest",
    "ShellEngineeringChangesetApplyRequest",
    "ShellEngineeringChangesetPreviewRequest",
    "ShellEngineeringIncidentAdvanceRequest",
    "ShellEngineeringPublicationRequest",
    "TerminalShell",
    "render_contexts",
    "render_engineering_result",
    "render_memory_response",
    "render_adaptation_response",
    "render_peer_response",
    "render_snapshot",
    "run_terminal",
]
