"""Resource budgeting and placement contracts."""

from fam_os.scheduler.configuration import (
    CONFIGURATION_CONTRACT_VERSION,
    VALIDATION_PROFILE_DOCUMENT_CONTRACT_VERSION,
    AcceleratorVisibility,
    AcceleratorRuntimeState,
    ComposedResourceConfiguration,
    ConfigurationCompositionRequest,
    ConfigurationDecision,
    ConfigurationDecisionKind,
    ConfigurationLayer,
    DiscoveredResourceState,
    ResourcePolicy,
    ResourceRestriction,
    SchedulerDefaults,
    ServiceResourceEnvelope,
    SessionResourceOverride,
    StorageRuntimeState,
    UserResourcePolicy,
    ValidationProfileConfiguration,
    ValidationProfileDocument,
    ValidationWorkloadMode,
    compose_resource_configuration,
)
from fam_os.scheduler.contracts import PlacementPlan, ResourceBudget
from fam_os.scheduler.hardware import (
    CpuProfile,
    GpuProfile,
    HardwareProfile,
    MemoryProfile,
    OperatingSystemProfile,
    RuntimeVersion,
    StorageProfile,
)
from fam_os.scheduler.live_contracts import (
    LIVE_RESOURCE_OBSERVATION_VERSION,
    LiveAcceleratorAvailability,
    LiveCpuAvailability,
    LiveMemoryAvailability,
    LiveStorageAvailability,
    ManagedServiceUsage,
    ObservationStatus,
    SchedulerResourceObservation,
)
from fam_os.scheduler.live_sampler import LiveResourceSampler
from fam_os.scheduler.context_contracts import (
    CONTEXT_MEMORY_CONTRACT_VERSION,
    ContextMemoryEstimate,
    ContextMemoryModelProfile,
    ContextMemoryReservation,
    ContextMemoryStrategy,
    ContextProfileSource,
)
from fam_os.scheduler.context_estimator import ContextMemoryEstimator
from fam_os.scheduler.residency_contracts import (
    EXPERT_RESIDENCY_CONTRACT_VERSION,
    ExpertResidencyCatalog,
    ExpertResidencyIdentity,
    ExpertResidencyRecord,
    ExpertResidencyState,
    ResidencyLease,
    ResidencyTransitionReason,
    initial_cold_residency_catalog,
)
from fam_os.scheduler.residency_repository import InMemoryExpertResidencyRepository
from fam_os.scheduler.residency_service import (
    ExpertResidencyService,
    ResidencyEvictionCoordinator,
)
from fam_os.scheduler.admission_contracts import (
    ADMISSION_CONTRACT_VERSION,
    AdmissionDecision,
    AdmissionRequest,
    AdmissionStatus,
    EvictionCandidate,
    ResidentWeightEstimate,
    WeightEstimateSource,
)
from fam_os.scheduler.admission_policy import DeterministicAdmissionPolicy
from fam_os.scheduler.baseline_contracts import (
    CPU_BASELINE_CONTRACT_VERSION,
    CPU_ONLY_ENVIRONMENT,
    CpuBaselineExpertAttempt,
    CpuOnlyBaselineReport,
)
from fam_os.scheduler.gpu_contracts import (
    GPU_PLACEMENT_CONTRACT_VERSION,
    GpuPlacementDecision,
    GpuPlacementEvidence,
    GpuPlacementRequest,
    FullWorkstationGpuReport,
)
from fam_os.scheduler.gpu_policy import DeterministicGpuPlacementPolicy
from fam_os.scheduler.storage_contracts import (
    STORAGE_PAGING_CONTRACT_VERSION,
    ArtifactCacheObservation,
    LoadCacheState,
    ModelLoadIoBudget,
    ModelLoadIoTrial,
    ModelStorageArtifact,
    StoragePagingEvidence,
)
from fam_os.scheduler.npu_contracts import (
    NPU_INVESTIGATION_CONTRACT_VERSION,
    NpuHardwareEvidence,
    NpuInvestigationOutcome,
    NpuInvestigationReport,
    NpuMicroExpertEvidence,
    NpuRuntimeEvidence,
)
from fam_os.scheduler.cache_contracts import (
    CACHE_POLICY_CONTRACT_VERSION,
    CACHE_POLICY_VERSION,
    CacheEntryState,
    CacheEvictionDecision,
    CachePolicyDecision,
    CachePolicyRequest,
    CacheTelemetryEntry,
    CacheTelemetrySnapshot,
    CacheTier,
    CacheTierPressure,
    CacheTierReclaim,
)
from fam_os.scheduler.cache_policy import DeterministicCacheRetentionPolicy
from fam_os.scheduler.replay_contracts import (
    POLICY_REPLAY_CONTRACT_VERSION,
    SchedulerPolicyKind,
    SchedulerPolicyReplayRecord,
    SchedulerPolicyReplayReport,
)
from fam_os.scheduler.prefetch_prediction import (
    PREFETCH_CONTRACT_VERSION,
    PREFETCH_PREDICTOR_VERSION,
    ArtifactAccessSequence,
    PrefetchCandidate,
    PrefetchPrediction,
    PrefetchPredictionRequest,
)
from fam_os.scheduler.prefetch_predictor import DeterministicTransitionPredictor
from fam_os.scheduler.prefetch_contracts import (
    PREFETCH_POLICY_VERSION,
    PredictivePrefetchReport,
    PrefetchAdmissionStatus,
    PrefetchExecutionEvidence,
    PrefetchPolicyDecision,
    PrefetchPolicyRequest,
    PrefetchResourceBudget,
)
from fam_os.scheduler.prefetch_policy import DeterministicPrefetchAdmissionPolicy
from fam_os.scheduler.resources import (
    COMPAT_CPU_16GB_PROFILE_ID,
    EFFECTIVE_RESOURCE_BUDGET_CONTRACT_VERSION,
    FULL_REFERENCE_WORKSTATION_PROFILE_ID,
    HOST_INVENTORY_CONTRACT_VERSION,
    AcceleratorKind,
    AcceleratorResourceBudget,
    CpuResourceBudget,
    EffectiveResourceBudget,
    HostAcceleratorInventory,
    HostCpuInventory,
    HostInventory,
    HostMemoryInventory,
    HostStorageInventory,
    MemoryResourceBudget,
    PressureReading,
    StorageMedium,
    StorageResourceBudget,
    ValidationProfilePurpose,
    ValidationProfileRef,
)

__all__ = [
    "CONFIGURATION_CONTRACT_VERSION",
    "VALIDATION_PROFILE_DOCUMENT_CONTRACT_VERSION",
    "AcceleratorVisibility",
    "AcceleratorRuntimeState",
    "ComposedResourceConfiguration",
    "ConfigurationCompositionRequest",
    "ConfigurationDecision",
    "ConfigurationDecisionKind",
    "ConfigurationLayer",
    "CpuProfile",
    "CpuResourceBudget",
    "COMPAT_CPU_16GB_PROFILE_ID",
    "EFFECTIVE_RESOURCE_BUDGET_CONTRACT_VERSION",
    "FULL_REFERENCE_WORKSTATION_PROFILE_ID",
    "GpuProfile",
    "HOST_INVENTORY_CONTRACT_VERSION",
    "HardwareProfile",
    "DiscoveredResourceState",
    "HostAcceleratorInventory",
    "HostCpuInventory",
    "HostInventory",
    "HostMemoryInventory",
    "HostStorageInventory",
    "MemoryProfile",
    "MemoryResourceBudget",
    "OperatingSystemProfile",
    "PlacementPlan",
    "PressureReading",
    "ResourceBudget",
    "ResourcePolicy",
    "ResourceRestriction",
    "RuntimeVersion",
    "AcceleratorKind",
    "AcceleratorResourceBudget",
    "EffectiveResourceBudget",
    "StorageMedium",
    "StorageProfile",
    "StorageResourceBudget",
    "StorageRuntimeState",
    "SchedulerDefaults",
    "ServiceResourceEnvelope",
    "SessionResourceOverride",
    "UserResourcePolicy",
    "ValidationProfileConfiguration",
    "ValidationProfileDocument",
    "ValidationWorkloadMode",
    "ValidationProfilePurpose",
    "ValidationProfileRef",
    "compose_resource_configuration",
    "LIVE_RESOURCE_OBSERVATION_VERSION",
    "LiveAcceleratorAvailability",
    "LiveCpuAvailability",
    "LiveMemoryAvailability",
    "LiveResourceSampler",
    "LiveStorageAvailability",
    "ManagedServiceUsage",
    "ObservationStatus",
    "SchedulerResourceObservation",
    "CONTEXT_MEMORY_CONTRACT_VERSION",
    "ContextMemoryEstimate",
    "ContextMemoryEstimator",
    "ContextMemoryModelProfile",
    "ContextMemoryReservation",
    "ContextMemoryStrategy",
    "ContextProfileSource",
    "EXPERT_RESIDENCY_CONTRACT_VERSION",
    "ExpertResidencyCatalog",
    "ExpertResidencyIdentity",
    "ExpertResidencyRecord",
    "ExpertResidencyService",
    "ExpertResidencyState",
    "InMemoryExpertResidencyRepository",
    "ResidencyEvictionCoordinator",
    "ResidencyLease",
    "ResidencyTransitionReason",
    "initial_cold_residency_catalog",
    "ADMISSION_CONTRACT_VERSION",
    "AdmissionDecision",
    "AdmissionRequest",
    "AdmissionStatus",
    "DeterministicAdmissionPolicy",
    "EvictionCandidate",
    "ResidentWeightEstimate",
    "WeightEstimateSource",
    "CPU_BASELINE_CONTRACT_VERSION",
    "CPU_ONLY_ENVIRONMENT",
    "CpuBaselineExpertAttempt",
    "CpuOnlyBaselineReport",
    "GPU_PLACEMENT_CONTRACT_VERSION",
    "DeterministicGpuPlacementPolicy",
    "GpuPlacementDecision",
    "GpuPlacementEvidence",
    "GpuPlacementRequest",
    "FullWorkstationGpuReport",
    "STORAGE_PAGING_CONTRACT_VERSION",
    "ArtifactCacheObservation",
    "LoadCacheState",
    "ModelLoadIoBudget",
    "ModelLoadIoTrial",
    "ModelStorageArtifact",
    "StoragePagingEvidence",
    "NPU_INVESTIGATION_CONTRACT_VERSION",
    "NpuHardwareEvidence",
    "NpuInvestigationOutcome",
    "NpuInvestigationReport",
    "NpuMicroExpertEvidence",
    "NpuRuntimeEvidence",
    "CACHE_POLICY_CONTRACT_VERSION", "CACHE_POLICY_VERSION", "CacheEntryState",
    "CacheEvictionDecision", "CachePolicyDecision", "CachePolicyRequest",
    "CacheTelemetryEntry", "CacheTelemetrySnapshot", "CacheTier",
    "CacheTierPressure", "CacheTierReclaim",
    "DeterministicCacheRetentionPolicy",
    "POLICY_REPLAY_CONTRACT_VERSION",
    "SchedulerPolicyKind",
    "SchedulerPolicyReplayRecord",
    "SchedulerPolicyReplayReport",
    "PREFETCH_CONTRACT_VERSION", "PREFETCH_PREDICTOR_VERSION", "PREFETCH_POLICY_VERSION",
    "ArtifactAccessSequence", "PrefetchCandidate", "PrefetchPrediction",
    "PrefetchPredictionRequest", "DeterministicTransitionPredictor",
    "PrefetchAdmissionStatus", "PrefetchResourceBudget", "PrefetchPolicyRequest",
    "PrefetchPolicyDecision", "PrefetchExecutionEvidence", "PredictivePrefetchReport",
    "DeterministicPrefetchAdmissionPolicy",
]
