"""Catalog of public Phase 2 serialized document roots."""

from __future__ import annotations

from fam_os.applications import (
    APPLICATION_ACTION_AUDIT_VERSION,
    APPLICATION_CONTRACT_VERSION,
    APPLICATION_FAILURE_CONTRACT_VERSION,
    ActionConfirmation,
    ActionPreparationRequest,
    ActionProposal,
    ActionResult,
    ApplicationActionAuditIntent,
    ApplicationActionAuditRecord,
    ApplicationFailure,
    ApplicationIdentity,
    ApplicationInstance,
    CapabilityDescriptor,
    CapabilityRegistryEntry,
    ConnectorEvent,
    ConnectorRegistration,
    ObservationRequest,
    ObservationResult,
    PermissionGrant,
)
from fam_os.applications.manifest import CONNECTOR_MANIFEST_CONTRACT_VERSION, ConnectorManifest
from fam_os.core.contracts import (
    CORE_CONTRACT_VERSION,
    LEGACY_TASK_RESULT_VERSION,
    TASK_RESULT_CONTRACT_VERSION,
    FAILURE_CONTRACT_VERSION,
    DegradationNotice,
    ExecutionPlan,
    FailureEnvelope,
    ResultCitation,
    TaskRequest,
    TaskResult,
    TaskResultV1Alpha1,
)
from fam_os.core.admission.contracts import RequestAuthorityGrant
from fam_os.core.engineering import (
    ENGINEERING_CONTRACT_VERSION,
    ChangeSetProposal,
    CheckpointDecision,
    DependencyPlan,
    DesignAssetManifest,
    EngineeringEvidence,
    EngineeringCapabilityUnavailable,
    EngineeringAuthorityGrant,
    EngineeringAuthorizationDecision,
    EngineeringAuthorizationRequest,
    EngineeringExecutionRecord,
    BreakGlassChallenge,
    BreakGlassDecision,
    EngineeringProposalResult,
    EngineeringPublicationProposal,
    EngineeringPublicationReceipt,
    EngineeringTaskEnvelope,
    FileOperation,
    GitOperation,
    ToolRecipe,
    ToolRun,
    OwnerGrantApproval,
    VerifiedChangeSetReceipt,
    WorkspaceSnapshot,
    CandidateApplyReceipt,
    CandidateArtifact,
    CandidateOperation,
    CandidateTransactionPreview,
    CandidateWorkspace,
    EngineeringSelfUpdatePolicy,
    DependencyResolutionReceipt,
    DependencyResolutionRequest,
    DesignAssetRecord,
    DesignBrief,
    DesignVerificationReceipt,
    EngineeringSandboxProfile,
    EngineeringToolReceipt,
    HostAdministrationChangeSet,
    HostAdministrationReceipt,
    GitLocalAction,
    GitLocalActionReceipt,
    GitPublicationApproval,
    GitPublicationLocalState,
    GitPublicationProposal,
    GitPublicationReceipt,
    GitRemoteRefObservation,
    GitRemoteRefObservationRequest,
    GitRepositoryObservation,
    LocalGitDeliveryRecord,
    EngineeringLoopState,
    EngineeringPressureSoakReport,
    EngineeringSecurityReview,
    InstalledEngineeringQualification,
    LanguageToolQualification,
    PolyglotRecipeMatrix,
    RawShellAuthorization,
    RuntimeDiagnosticReceipt,
    RuntimeDiagnosticRequest,
    RuntimeDiagnosticQualification,
    RuntimeDiagnosticQualificationMatrix,
    DatabaseBackupReceipt,
    DatabaseChangePlan,
    DatabaseExecutionPermit,
    DatabaseTarget,
    IntegrationEnvironmentPlan,
    NaturalIntegrationEnvironmentDeclaration,
    IntegrationEnvironmentReceipt,
    IntegrationEnvironmentStartResult,
    IntegrationExecutionPermit,
    IntegrationNetworkAttachment,
    IntegrationNetworkEnforcementRequest,
    IntegrationNetworkLease,
    IntegrationNetworkUsage,
    IntegrationServiceSpec,
    DatabaseVerificationReceipt,
    DatabasePostapplyReceipt,
    PostgreSQLIntegrationVerificationPlan,
    PostgreSQLIntegrationVerificationReceipt,
    SecretUseAuthorization,
    SecretUseReceipt,
    SignedToolRecipe,
    SignedDocumentationRecipe,
    DocumentationGenerationRequest,
    DocumentationGovernanceBinding,
    DocumentationRequirementSelection,
    DocumentationStalenessReport,
    GeneratedDocumentationReceipt,
    RequirementTraceabilityRecord,
    EngineeringReviewCheckpoint,
    EngineeringReviewResolutionReceipt,
    EngineeringReviewSelection,
    EngineeringReviewWaiverDecision,
    SignedEngineeringReviewerRecipe,
    EngineeringIncidentState,
    EngineeringIncidentEvidenceReceipt,
    EngineeringTaskDefinition,
    EngineeringPreparationResult,
    CandidateEditRecord,
    CandidateVerificationRecord,
    CandidateChangesetRecord,
    CandidateGenerationContext,
    CandidateGenerationRecord,
    GeneratedCandidatePlan,
)
from fam_os.core.lifecycle.attempt_contracts import AttemptBudgetPolicy
from fam_os.core.engineering.repository import (
    ArchitectureProposal,
    EngineeringTaskGraph,
    EngineeringTaskGraphEvent,
    RepositoryAnalysis,
    RepositoryAnalysisRequest,
    RepositoryEvidenceBundle,
)
from fam_os.core.lifecycle.contracts import PlanInstanceSnapshot, PlanLifecycleEvent
from fam_os.core.lifecycle.control_contracts import PlanDeadlinePolicy
from fam_os.core.lifecycle.final_contracts import (
    AcceptanceEvidenceRecord,
    CandidateEvidenceRecord,
)
from fam_os.core.production import (
    APPLICATION_EXECUTION_VERSION,
    ApplicationExecutionRecord,
    INFERENCE_EXECUTION_VERSION,
    InferenceExecutionRecord,
    RuntimeModelEntry,
    RuntimeModelSelection,
)
from fam_os.experts import (
    EXPERT_BENCHMARK_METADATA_VERSION,
    EXPERT_COMPATIBILITY_CONTRACT_VERSION,
    EXPERT_MANIFEST_CONTRACT_VERSION,
    EXPERT_ROUTING_METADATA_VERSION,
    EXPERT_RUNTIME_BINDING_VERSION,
    LEGACY_EXPERT_MANIFEST_CONTRACT_VERSION,
    ExpertBenchmarkRun,
    ExpertCompatibilityReport,
    ExpertManifest,
    ExpertManifestV1Alpha1,
    ExpertRoutingEmbedding,
    ExpertRuntimeBinding,
    MIXED_BENCHMARK_CONTRACT_VERSION,
    MixedBenchmarkReport,
    MixedBenchmarkSuite,
    MICRO_EXPERT_CONTRACT_VERSION,
    MicroExpertAdvice,
    MicroExpertBenchmarkReport,
    ESCALATION_TRACE_CONTRACT_VERSION,
    EscalationTraceReport,
    RETRIEVAL_EVIDENCE_CONTRACT_VERSION,
    RETRIEVAL_TIERS_CONTRACT_VERSION,
    RetrievalTierEvidence,
    VerifiedRetrievalResult,
    MATH_EVIDENCE_CONTRACT_VERSION,
    MATH_EXPERT_CONTRACT_VERSION,
    MathExpertEvidence,
    MathReasoningAdvice,
    MathSolverRequest,
    MathSolverResult,
    MEDIA_EVIDENCE_CONTRACT_VERSION,
    MediaExpertEvidence,
    EFFICIENCY_REPORT_CONTRACT_VERSION,
    ExpertEfficiencyReport,
    EXPERT_EVOLUTION_CONTRACT_VERSION,
    ExpertEvolutionProposal,
    ExpertEvolutionReport,
    ExpertPerformanceSlice,
    PHASE9_EXIT_CONTRACT_VERSION,
    Phase9ExitEvidence,
)
from fam_os.memory import (
    MEMORY_LIFECYCLE_CONTRACT_VERSION,
    MEMORY_RECORD_MANIFEST_CONTRACT_VERSION,
    MemoryDeletionReceipt,
    MemoryDeletionRequest,
    MemoryExpiryEvaluation,
    MemoryRecordManifest,
    MEMORY_ACCESS_CONTRACT_VERSION,
    MemoryAccessContext,
    DOCUMENT_INDEX_CONTRACT_VERSION,
    DocumentIndexApproval,
    DocumentIndexEvidence,
    DocumentRetrievalHit,
    IndexedDocumentChunk,
    DOCUMENT_INDEX_GRANT_VERSION,
    DocumentIndexGrant,
    DocumentIndexReceipt,
    MEMORY_RELEVANCE_CONTRACT_VERSION,
    MemoryRelevanceDecision,
    MemoryRetrievalCandidate,
    MEMORY_MANAGEMENT_CONTRACT_VERSION,
    DocumentCorrectionRequest,
    DocumentDeletionRequest,
    DocumentExpirationRequest,
    DocumentInspection,
    DocumentManagementReceipt,
    MemoryDocumentExport,
    MemoryManagementEvidence,
    MEMORY_ENCRYPTION_CONTRACT_VERSION,
    MemoryEncryptionEvidence,
    MEMORY_QUALITY_CONTRACT_VERSION,
    MemoryQualityPrivacyReport,
    PHASE10_EXIT_CONTRACT_VERSION,
    Phase10ExitEvidence,
)
from fam_os.adaptation import (
    OUTCOME_PREDICTION_CONTRACT_VERSION,
    VerifiedOutcomeObservation,
    WorkflowOutcomePrediction,
    PREFERENCE_CONTRACT_VERSION,
    PreferenceResetReceipt,
    UserPreferenceProfile,
    RESOURCE_ADAPTATION_CONTRACT_VERSION,
    OperatingPolicyDecision,
    OperatingState,
    ADAPTATION_DRIFT_CONTRACT_VERSION,
    AdaptationDriftReport,
    AdaptationRollbackReceipt,
    AdaptationSnapshot,
    PHASE11_EXIT_CONTRACT_VERSION,
    Phase11ExitEvidence,
    VERIFIED_LEARNING_CONTRACT_VERSION,
    VerifiedLearningOutcome,
    LIVE_ADAPTATION_CONTRACT_VERSION,
    LiveAdaptationSnapshot,
    ModelPrewarmReceipt,
    LIVE_ADAPTATION_CONTROL_VERSION,
    AdaptationHealthSample,
    AdaptationHealthSummary,
    AdaptationInferenceObservation,
    LiveAdaptationControlReceipt,
    LiveAdaptationControlRequest,
    LiveAdaptationControlState,
    LiveAdaptationDriftReport,
)
from fam_os.fabric import (
    DEVICE_IDENTITY_CONTRACT_VERSION,
    DEVICE_PAIRING_CONTRACT_VERSION,
    MUTUAL_TLS_CONTRACT_VERSION,
    PEER_ENROLLMENT_CONTRACT_VERSION,
    PEER_CONTROL_CONTRACT_VERSION,
    PEER_SERVICE_CONFIGURATION_VERSION,
    PEER_STATE_CONTRACT_VERSION,
    TRUSTED_PEER_DIRECTORY_VERSION,
    REMOTE_CONTEXT_CONTRACT_VERSION,
    REMOTE_EXECUTION_CONTRACT_VERSION,
    REMOTE_EXECUTION_EVIDENCE_VERSION,
    REMOTE_RECOVERY_EVIDENCE_VERSION,
    PHYSICAL_HOST_EVIDENCE_VERSION,
    PHYSICAL_PEER_OBSERVATION_VERSION,
    AuthenticatedPeer,
    DeviceEnrollmentChallenge,
    DeviceEnrollmentRecord,
    DeviceEnrollmentRequest,
    DeviceIdentity,
    DevicePairingApproval,
    DevicePairingOffer,
    PeerEndpoint,
    PeerEnrollmentRecord,
    PeerControlRequest,
    PeerControlResponse,
    PeerServiceConfiguration,
    PeerCapabilityDeclaration,
    PeerManagementRequest,
    PeerManagementReceipt,
    PeerPerformanceObservation,
    PeerPrivacyPolicyRecord,
    TrustedPeerDirectoryEntry,
    RemoteContextDisclosureEvidence,
    RemoteContextEnvelope,
    RemoteContextReceipt,
    RemoteContextSendRequest,
    RemoteRawContextFragment,
    RemoteTaskDescriptor,
    RemoteExecutionAuthority,
    RemoteExecutionPlan,
    RemoteExecutionRequest,
    RemoteExecutionResult,
    RemoteExecutionEvidence,
    RemoteRecoveryEvidence,
    PhysicalHostEvidence,
    PhysicalPeerObservation,
    REMOTE_PRIVACY_CONTRACT_VERSION,
    RemoteContextRequest,
    RemoteExpertCapability,
    RemotePrivacyDecision,
    RemotePrivacyPolicy,
    FABRIC_TRANSPORT_CONTRACT_VERSION,
    FabricEncryptedEnvelope,
    FabricHandshake,
    FABRIC_SCHEDULING_CONTRACT_VERSION,
    FabricRouteCandidate,
    FabricRouteDecision,
    FABRIC_RECOVERY_CONTRACT_VERSION,
    FabricRecoveryDecision,
    FABRIC_DEMO_CONTRACT_VERSION,
    MultiDeviceDemoReport,
)
from fam_os.expert_factory import (
    EXPERT_DISCOVERY_CONTRACT_VERSION, FACTORY_DATASET_PROVENANCE_VERSION,
    FACTORY_FAILURE_DISCOVERY_VERSION,
    FACTORY_SEALED_DATASET_VERSION,
    FACTORY_TRAINING_APPROVAL_VERSION,
    FACTORY_TRAINING_BACKEND_VERSION,
    FACTORY_RESOURCE_ADMISSION_VERSION,
    FACTORY_EVALUATION_VERSION,
    FACTORY_CONVERSION_VERSION,
    FACTORY_SPECIALIST_RELEASE_VERSION,
    FACTORY_CANARY_VERSION,
    FACTORY_SPECIALIST_LIFECYCLE_VERSION,
    FACTORY_LIFECYCLE_CONTRACT_VERSION,
    FACTORY_OBJECTIVE_CONTRACT_VERSION, FACTORY_PIPELINE_CONTRACT_VERSION,
    FACTORY_QUANTIZATION_CONTRACT_VERSION, FACTORY_REGRESSION_CONTRACT_VERSION,
    FACTORY_RELEASE_CONTRACT_VERSION, FACTORY_TRAINING_CONTRACT_VERSION,
    AdapterTrainingJob, AdapterTrainingPlan, AdapterTrainingRecipe,
    FactoryConversionApproval, FactoryConversionEnvironment,
    FactoryConversionReceipt,
    FactorySpecialistPackageReceipt, FactorySpecialistReleaseLineage,
    FactoryActivationDecision, FactoryCanaryApproval, FactoryCanaryReport,
    FactorySpecialistLifecycleReceipt, FactorySpecialistLifecycleRequest,
    ApprovedBaseModel, CapturedDatasetSource, DatasetLeakageFinding,
    DatasetLeakageReport, DatasetSplitPolicy,
    DistillationPlan, EvaluationPlan,
    ExpertComparisonDecision, ExpertEvaluationReport,
    FactoryCapabilityProposal, FactoryEvaluationApproval,
    FactoryEvaluationPolicy, FactoryLifecycleReport, FactoryTrainingApproval,
    FailureTrace, FailureTraceCluster, HardwareTrainingMetrics,
    HeldOutAccessReceipt, MissingCapabilityProposal,
    PairedEvaluationMeasurement, PublishedExpertPackage, QuantizedVariant,
    RegressionGateResult, SealedDatasetBlobReceipt, SealedDatasetPartition,
    SealedFactoryDataset,
    SyntheticExampleProposal, SyntheticExampleReview,
    TeacherDataset, TrainedMicroExpert, TrainingCaptureGrant,
    TrainingApprovalConsumption, TrainingApprovalRevocation,
    TrainingBackendEnvironment, TrainingTerminalReceipt,
    TrainingAdmissionDecision, TrainingResourceSnapshot,
    TrainingCaptureRevocation, TrainingResourceBudget,
    VerifiedFailureCluster, VerifiedFailureTrace,
)
from fam_os.console.contracts import CONSOLE_CONTRACT_VERSION, ConsoleSnapshot
from fam_os.product.benchmark_publication import (
    BENCHMARK_PUBLICATION_VERSION, BenchmarkPublication,
)
from fam_os.product.integration_coverage import (
    INTEGRATION_COVERAGE_VERSION,
    IntegrationCoverageManifest,
)
from fam_os.product.linux_installation import (
    INSTALL_CONTRACT_VERSION, InstallationReceipt,
)
from fam_os.product.phase14_exit import PHASE14_EXIT_VERSION, Phase14ExitEvidence
from fam_os.product.phase15_exit import PHASE15_EXIT_VERSION, Phase15ExitEvidence
from fam_os.product.recovery_mode import RECOVERY_CONTRACT_VERSION, RecoveryDecision
from fam_os.product.restart_recovery import (
    RESTART_RECOVERY_VERSION,
    PersistedActionRecord,
    RestartRecoveryDecision,
)
from fam_os.product.request_recovery import (
    REQUEST_RECOVERY_VERSION,
    RequestRecoveryRecord,
    RequestRestartDecision,
)
from fam_os.product.worker_budgets import (
    WORKER_BUDGET_VERSION,
    WorkerBudgetPolicy,
    WorkerLimitPlan,
)
from fam_os.product.soak_contracts import SOAK_CONTRACT_VERSION, SoakReport
from fam_os.product.update_contracts import UPDATE_CONTRACT_VERSION, UpdateReceipt
from fam_os.product.update_contracts import SignedReleaseManifest
from fam_os.security.review import SecurityReviewReport
from fam_os.registry import (
    REGISTRY_TRUST_CONTRACT_VERSION,
    PackageSignature,
    PackageTrustPolicy,
    PackageValidationReport,
)
from fam_os.registry.lifecycle_contracts import (
    PACKAGE_LIFECYCLE_CONTRACT_VERSION,
    ExpertPackageInstallationState,
)
from fam_os.routing import ROUTING_CONTRACT_VERSION, RoutingRequest, RoutingResult
from fam_os.core.lifecycle.global_budget import (
    GLOBAL_ATTEMPT_BUDGET_VERSION,
    AttemptBudgetReservation,
    GlobalAttemptBudget,
    GlobalAttemptBudgetSnapshot,
)
from fam_os.scheduler.resources import (
    EFFECTIVE_RESOURCE_BUDGET_CONTRACT_VERSION,
    HOST_INVENTORY_CONTRACT_VERSION,
    EffectiveResourceBudget,
    HostInventory,
)
from fam_os.scheduler.frequency_learning import (
    EXPERT_FREQUENCY_CONTRACT_VERSION,
    ExpertFrequencyProfile,
)
from fam_os.scheduler.live_contracts import (
    LIVE_RESOURCE_OBSERVATION_VERSION,
    SchedulerResourceObservation,
)
from fam_os.scheduler.context_contracts import (
    CONTEXT_MEMORY_CONTRACT_VERSION,
    ContextMemoryEstimate,
    ContextMemoryModelProfile,
    ContextMemoryReservation,
)
from fam_os.scheduler.residency_contracts import (
    EXPERT_RESIDENCY_CONTRACT_VERSION,
    ExpertResidencyCatalog,
)
from fam_os.scheduler.admission_contracts import (
    ADMISSION_CONTRACT_VERSION,
    AdmissionDecision,
    AdmissionRequest,
)
from fam_os.scheduler.baseline_contracts import (
    CPU_BASELINE_CONTRACT_VERSION,
    CpuOnlyBaselineReport,
)
from fam_os.scheduler.gpu_contracts import (
    GPU_PLACEMENT_CONTRACT_VERSION,
    GpuPlacementDecision,
    GpuPlacementEvidence,
    GpuPlacementRequest,
    FullWorkstationGpuReport,
)
from fam_os.scheduler.storage_contracts import (
    STORAGE_PAGING_CONTRACT_VERSION,
    ArtifactCacheObservation,
    ModelStorageArtifact,
    StoragePagingEvidence,
)
from fam_os.scheduler.npu_contracts import (
    NPU_INVESTIGATION_CONTRACT_VERSION,
    NpuInvestigationReport,
)
from fam_os.scheduler.cache_contracts import (
    CACHE_POLICY_CONTRACT_VERSION,
    CachePolicyDecision,
    CachePolicyRequest,
    CacheTelemetrySnapshot,
)
from fam_os.scheduler.replay_contracts import (
    POLICY_REPLAY_CONTRACT_VERSION,
    SchedulerPolicyReplayReport,
)
from fam_os.scheduler.prefetch_prediction import (
    PREFETCH_CONTRACT_VERSION,
    PrefetchPrediction,
    PrefetchPredictionRequest,
)
from fam_os.scheduler.prefetch_contracts import (
    PredictivePrefetchReport,
    PrefetchPolicyDecision,
    PrefetchPolicyRequest,
)
from fam_os.scheduler.configuration import (
    CONFIGURATION_CONTRACT_VERSION,
    ComposedResourceConfiguration,
    ConfigurationCompositionRequest,
    DiscoveredResourceState,
    SchedulerDefaults,
    SessionResourceOverride,
    UserResourcePolicy,
    ValidationProfileConfiguration,
    VALIDATION_PROFILE_DOCUMENT_CONTRACT_VERSION,
    ValidationProfileDocument,
)
from fam_os.shell import (
    LEGACY_SHELL_SNAPSHOT_VERSION,
    SHELL_CONTRACT_VERSION,
    SHELL_SNAPSHOT_CONTRACT_VERSION,
    SHELL_MEMORY_CONTRACT_VERSION,
    SHELL_ADAPTATION_CONTRACT_VERSION,
    SHELL_PEER_CONTRACT_VERSION,
    SHELL_ENGINEERING_AUTHORITY_VERSION,
    SHELL_INTEGRATION_ENVIRONMENT_VERSION,
    SHELL_ENGINEERING_SECRET_VERSION,
    SHELL_ENGINEERING_LOOP_VERSION,
    ShellAskCommand,
    ShellCancelCommand,
    ShellDecisionCommand,
    ShellSessionSnapshot,
    ShellSessionSnapshotV1Alpha1,
    ShellSnapshotQuery,
    ShellVerifiedAskCommand,
    ShellMemoryQuery,
    ShellMemoryResponse,
    ShellAdaptationQuery,
    ShellAdaptationResponse,
    ShellPeerProbeRequest,
    ShellPeerQuery,
    ShellPeerResponse,
    ShellEngineeringActivationRequest,
    ShellEngineeringAuthorityResponse,
    ShellEngineeringContextRequest,
    ShellEngineeringGrantQuery,
    ShellEngineeringRevocationRequest,
    ShellIntegrationEnvironmentControlRequest,
    ShellIntegrationEnvironmentQuery,
    ShellIntegrationEnvironmentResponse,
    ShellIntegrationEnvironmentStartRequest,
    ShellEngineeringSecretMutation,
    ShellEngineeringSecretQuery,
    ShellEngineeringSecretResponse,
    ShellEngineeringLoopMutation,
    ShellEngineeringLoopQuery,
    ShellEngineeringLoopResponse,
    ShellEngineeringLoopStartRequest,
    ShellEngineeringCandidateEditRequest,
    ShellEngineeringCandidateVerificationRequest,
    ShellEngineeringCandidateReverificationRequest,
    ShellEngineeringChangesetApplyRequest,
    ShellEngineeringChangesetPreviewRequest,
    ShellEngineeringIncidentAdvanceRequest,
    ShellEngineeringPublicationRequest,
)
from fam_os.schemas.descriptor import SchemaDescriptor
from fam_os.verification import (
    LEGACY_VERIFICATION_DECLARATION_VERSION,
    MEDIA_VERIFICATION_VERSION,
    VERIFICATION_DECLARATION_VERSION,
    VERIFICATION_RUN_VERSION,
    VERIFIER_ACTIVATION_DECISION_VERSION,
    VERIFIER_MANIFEST_CONTRACT_VERSION,
    VERIFIER_RUNTIME_BINDING_VERSION,
    VERIFIER_TRUST_POLICY_VERSION,
    MediaArtifactTextReport,
    VerificationDeclaration,
    VerificationDeclarationV1Alpha1,
    VerificationRunRecord,
    VerifierActivationDecision,
    VerifierManifest,
    VerifierRuntimeBinding,
    VerifierTrustPolicy,
)
from fam_os.verification.python.quality import (
    PYTHON_QUALITY_CONTRACT_VERSION,
    PythonQualityReport,
)
from fam_os.verification.language_quality import (
    LANGUAGE_QUALITY_CONTRACT_VERSION,
    LanguageQualityReport,
)
from fam_os.verification.math_contracts import (
    MATH_VERIFICATION_CONTRACT_VERSION,
    MathVerificationReport,
    MathVerificationRequest,
)
from fam_os.verification.retrieval import (
    RETRIEVAL_VERIFICATION_CONTRACT_VERSION,
    RetrievalVerificationReport,
)


def _entry(
    family: str,
    version: str,
    root: type[object],
    title: str,
    schema_version: str = "v1alpha1",
) -> SchemaDescriptor:
    return SchemaDescriptor(f"{family}/{schema_version}", version, root, title)


SCHEMA_DESCRIPTORS = (
    _entry("fam.core.task-request", CORE_CONTRACT_VERSION, TaskRequest, "FAM task request"),
    _entry("fam.core.execution-plan", CORE_CONTRACT_VERSION, ExecutionPlan, "FAM execution plan"),
    _entry(
        "fam.core.task-result", LEGACY_TASK_RESULT_VERSION,
        TaskResultV1Alpha1, "FAM task result",
    ),
    _entry(
        "fam.core.task-result", TASK_RESULT_CONTRACT_VERSION,
        TaskResult, "Typed FAM task result", "v1alpha2",
    ),
    _entry("fam.core.result-citation", CORE_CONTRACT_VERSION, ResultCitation, "Verified result citation"),
    _entry("fam.core.request-authority", CORE_CONTRACT_VERSION, RequestAuthorityGrant, "Request authority grant"),
    _entry("fam.core.plan-instance", CORE_CONTRACT_VERSION, PlanInstanceSnapshot, "Durable plan lifecycle snapshot"),
    _entry("fam.core.plan-event", CORE_CONTRACT_VERSION, PlanLifecycleEvent, "Durable plan lifecycle event"),
    _entry("fam.core.attempt-policy", CORE_CONTRACT_VERSION, AttemptBudgetPolicy, "Plan attempt policy"),
    _entry("fam.core.deadline-policy", CORE_CONTRACT_VERSION, PlanDeadlinePolicy, "Plan deadline policy"),
    _entry("fam.core.candidate-evidence", CORE_CONTRACT_VERSION, CandidateEvidenceRecord, "Candidate result evidence"),
    _entry("fam.core.acceptance-evidence", CORE_CONTRACT_VERSION, AcceptanceEvidenceRecord, "Acceptance result evidence"),
    _entry("fam.core.engineering-task", ENGINEERING_CONTRACT_VERSION, EngineeringTaskEnvelope, "Owner-delegated engineering task"),
    _entry("fam.core.workspace-snapshot", ENGINEERING_CONTRACT_VERSION, WorkspaceSnapshot, "Immutable engineering workspace snapshot"),
    _entry("fam.core.file-operation", ENGINEERING_CONTRACT_VERSION, FileOperation, "Proposed workspace file operation"),
    _entry("fam.core.change-set", ENGINEERING_CONTRACT_VERSION, ChangeSetProposal, "Bounded engineering change-set proposal"),
    _entry("fam.core.tool-recipe", ENGINEERING_CONTRACT_VERSION, ToolRecipe, "Authorized deterministic tool recipe"),
    _entry("fam.core.tool-run", ENGINEERING_CONTRACT_VERSION, ToolRun, "Observed engineering tool run"),
    _entry("fam.core.dependency-plan", ENGINEERING_CONTRACT_VERSION, DependencyPlan, "Auditable dependency change plan"),
    _entry("fam.core.design-assets", ENGINEERING_CONTRACT_VERSION, DesignAssetManifest, "Verified design asset manifest"),
    _entry("fam.core.git-operation", ENGINEERING_CONTRACT_VERSION, GitOperation, "Authorized Git operation"),
    _entry("fam.core.checkpoint-decision", ENGINEERING_CONTRACT_VERSION, CheckpointDecision, "Owner checkpoint decision"),
    _entry("fam.core.engineering-evidence", ENGINEERING_CONTRACT_VERSION, EngineeringEvidence, "Aggregate engineering execution evidence"),
    _entry("fam.core.engineering-proposal-result", ENGINEERING_CONTRACT_VERSION, EngineeringProposalResult, "Engineering change-set proposal result"),
    _entry("fam.core.verified-change-set", ENGINEERING_CONTRACT_VERSION, VerifiedChangeSetReceipt, "Independently verified change-set receipt"),
    _entry("fam.core.publication-proposal", ENGINEERING_CONTRACT_VERSION, EngineeringPublicationProposal, "Separately approved engineering publication proposal"),
    _entry("fam.core.publication-receipt", ENGINEERING_CONTRACT_VERSION, EngineeringPublicationReceipt, "Postcondition-verified publication receipt"),
    _entry("fam.core.engineering-unavailable", ENGINEERING_CONTRACT_VERSION, EngineeringCapabilityUnavailable, "Unavailable engineering capability result"),
    _entry("fam.core.engineering-grant", ENGINEERING_CONTRACT_VERSION, EngineeringAuthorityGrant, "Owner-bounded engineering authority grant"),
    _entry("fam.core.engineering-grant-approval", ENGINEERING_CONTRACT_VERSION, OwnerGrantApproval, "Authenticated owner engineering grant approval"),
    _entry("fam.core.engineering-authorization-request", ENGINEERING_CONTRACT_VERSION, EngineeringAuthorizationRequest, "Engineering effect authorization request"),
    _entry("fam.core.engineering-authorization-decision", ENGINEERING_CONTRACT_VERSION, EngineeringAuthorizationDecision, "Deterministic engineering authorization decision"),
    _entry("fam.core.engineering-break-glass", ENGINEERING_CONTRACT_VERSION, BreakGlassChallenge, "Exact-consequence engineering break-glass challenge"),
    _entry("fam.core.engineering-break-glass-decision", ENGINEERING_CONTRACT_VERSION, BreakGlassDecision, "Authenticated engineering break-glass decision"),
    _entry("fam.core.engineering-execution", ENGINEERING_CONTRACT_VERSION, EngineeringExecutionRecord, "Truthfully labelled engineering execution record"),
    _entry("fam.core.repository-evidence", ENGINEERING_CONTRACT_VERSION, RepositoryEvidenceBundle, "Bounded read-only repository evidence"),
    _entry("fam.core.repository-analysis-request", ENGINEERING_CONTRACT_VERSION, RepositoryAnalysisRequest, "Bounded repository analysis request"),
    _entry("fam.core.repository-analysis", ENGINEERING_CONTRACT_VERSION, RepositoryAnalysis, "Evidence-bound repository analysis"),
    _entry("fam.core.architecture-proposal", ENGINEERING_CONTRACT_VERSION, ArchitectureProposal, "Decision-complete architecture proposal"),
    _entry("fam.core.engineering-task-graph", ENGINEERING_CONTRACT_VERSION, EngineeringTaskGraph, "Bounded engineering task graph"),
    _entry("fam.core.engineering-task-graph-event", ENGINEERING_CONTRACT_VERSION, EngineeringTaskGraphEvent, "Append-only engineering task graph event"),
    _entry("fam.core.candidate-artifact", ENGINEERING_CONTRACT_VERSION, CandidateArtifact, "Digest-bound candidate workspace artifact"),
    _entry("fam.core.candidate-operation", ENGINEERING_CONTRACT_VERSION, CandidateOperation, "Typed candidate workspace operation"),
    _entry("fam.core.candidate-workspace", ENGINEERING_CONTRACT_VERSION, CandidateWorkspace, "Isolated candidate workspace baseline"),
    _entry("fam.core.candidate-preview", ENGINEERING_CONTRACT_VERSION, CandidateTransactionPreview, "Approval-ready candidate transaction preview"),
    _entry("fam.core.candidate-apply-receipt", ENGINEERING_CONTRACT_VERSION, CandidateApplyReceipt, "Journaled candidate reconciliation receipt"),
    _entry("fam.core.engineering-self-update-policy", ENGINEERING_CONTRACT_VERSION, EngineeringSelfUpdatePolicy, "Source-edit and runtime-protection boundary"),
    _entry("fam.core.signed-tool-recipe", ENGINEERING_CONTRACT_VERSION, SignedToolRecipe, "Signed typed engineering tool recipe"),
    _entry("fam.core.engineering-sandbox-profile", ENGINEERING_CONTRACT_VERSION, EngineeringSandboxProfile, "Transient candidate sandbox profile"),
    _entry("fam.core.raw-shell-authorization", ENGINEERING_CONTRACT_VERSION, RawShellAuthorization, "Exact single-use raw-shell authorization"),
    _entry("fam.core.runtime-diagnostic-request", ENGINEERING_CONTRACT_VERSION, RuntimeDiagnosticRequest, "Bounded signed runtime diagnostic request"),
    _entry("fam.core.runtime-diagnostic-receipt", ENGINEERING_CONTRACT_VERSION, RuntimeDiagnosticReceipt, "Sanitized runtime diagnostic evidence receipt"),
    _entry("fam.core.runtime-diagnostic-qualification", ENGINEERING_CONTRACT_VERSION, RuntimeDiagnosticQualification, "Physical positive and negative diagnostic qualification"),
    _entry("fam.core.runtime-diagnostic-matrix", ENGINEERING_CONTRACT_VERSION, RuntimeDiagnosticQualificationMatrix, "Fail-closed complete diagnostic qualification matrix"),
    _entry("fam.core.database-target", ENGINEERING_CONTRACT_VERSION, DatabaseTarget, "Exact local or secret-referenced database target"),
    _entry("fam.core.database-change-plan", ENGINEERING_CONTRACT_VERSION, DatabaseChangePlan, "Migration fixture backup and rollback plan"),
    _entry("fam.core.database-execution-permit", ENGINEERING_CONTRACT_VERSION, DatabaseExecutionPermit, "Expiring changeset and host bound database permit"),
    _entry("fam.core.database-backup-receipt", ENGINEERING_CONTRACT_VERSION, DatabaseBackupReceipt, "Consistent encrypted database backup evidence"),
    _entry("fam.core.database-verification-receipt", ENGINEERING_CONTRACT_VERSION, DatabaseVerificationReceipt, "Migration transaction restore and postcondition evidence"),
    _entry("fam.core.database-postapply-receipt", ENGINEERING_CONTRACT_VERSION, DatabasePostapplyReceipt, "Read-only exact owner database post-apply evidence"),
    _entry("fam.core.postgresql-integration-verification-plan", ENGINEERING_CONTRACT_VERSION, PostgreSQLIntegrationVerificationPlan, "Candidate-only reversible PostgreSQL migration verification plan"),
    _entry("fam.core.postgresql-integration-verification-receipt", ENGINEERING_CONTRACT_VERSION, PostgreSQLIntegrationVerificationReceipt, "Encrypted backup rollback replay transaction and restore evidence"),
    _entry("fam.core.integration-service", ENGINEERING_CONTRACT_VERSION, IntegrationServiceSpec, "Bounded integration service specification"),
    _entry("fam.core.natural-integration-declaration", ENGINEERING_CONTRACT_VERSION, NaturalIntegrationEnvironmentDeclaration, "Fixed-template natural integration service declaration"),
    _entry("fam.core.integration-environment", ENGINEERING_CONTRACT_VERSION, IntegrationEnvironmentPlan, "Task-bound service browser container or local-cluster environment"),
    _entry("fam.core.integration-environment-permit", ENGINEERING_CONTRACT_VERSION, IntegrationExecutionPermit, "Expiring decision-bound integration environment permit"),
    _entry("fam.core.integration-network-usage", ENGINEERING_CONTRACT_VERSION, IntegrationNetworkUsage, "Destination and byte-accounted allowlisted egress evidence"),
    _entry("fam.core.integration-network-attachment", ENGINEERING_CONTRACT_VERSION, IntegrationNetworkAttachment, "Broker-owned provider-specific network attachment"),
    _entry("fam.core.integration-network-request", ENGINEERING_CONTRACT_VERSION, IntegrationNetworkEnforcementRequest, "Exact external egress enforcement request"),
    _entry("fam.core.integration-network-lease", ENGINEERING_CONTRACT_VERSION, IntegrationNetworkLease, "Broker-owned integration network attachment lease"),
    _entry("fam.core.integration-environment-receipt", ENGINEERING_CONTRACT_VERSION, IntegrationEnvironmentReceipt, "Health and cleanup bound integration environment evidence"),
    _entry("fam.core.integration-environment-start", ENGINEERING_CONTRACT_VERSION, IntegrationEnvironmentStartResult, "Permit and plan digest bound integration environment start result"),
    _entry("fam.core.signed-documentation-recipe", ENGINEERING_CONTRACT_VERSION, SignedDocumentationRecipe, "Release-signed bounded documentation generator recipe"),
    _entry("fam.core.documentation-generation-request", ENGINEERING_CONTRACT_VERSION, DocumentationGenerationRequest, "Candidate-bound governed generated-content request"),
    _entry("fam.core.documentation-governance-binding", ENGINEERING_CONTRACT_VERSION, DocumentationGovernanceBinding, "Candidate-rehashed generated-content governance binding"),
    _entry("fam.core.documentation-requirement-selection", ENGINEERING_CONTRACT_VERSION, DocumentationRequirementSelection, "Policy-bound generated-content requirement selection"),
    _entry("fam.core.generated-documentation-receipt", ENGINEERING_CONTRACT_VERSION, GeneratedDocumentationReceipt, "Source and generator bound generated-content receipt"),
    _entry("fam.core.documentation-staleness-report", ENGINEERING_CONTRACT_VERSION, DocumentationStalenessReport, "Deterministic generated-output staleness report"),
    _entry("fam.core.requirement-traceability", ENGINEERING_CONTRACT_VERSION, RequirementTraceabilityRecord, "Requirement implementation test and evidence trace"),
    _entry("fam.core.engineering-review-checkpoint", ENGINEERING_CONTRACT_VERSION, EngineeringReviewCheckpoint, "Independent blocking multi-discipline review checkpoint"),
    _entry("fam.core.engineering-review-selection", ENGINEERING_CONTRACT_VERSION, EngineeringReviewSelection, "Policy-selected exact independent review disciplines"),
    _entry("fam.core.signed-engineering-reviewer", ENGINEERING_CONTRACT_VERSION, SignedEngineeringReviewerRecipe, "Release-signed independent reviewer recipe"),
    _entry("fam.core.engineering-review-resolution", ENGINEERING_CONTRACT_VERSION, EngineeringReviewResolutionReceipt, "Typed remediation and verification evidence resolving one finding"),
    _entry("fam.core.engineering-review-waiver", ENGINEERING_CONTRACT_VERSION, EngineeringReviewWaiverDecision, "Owner-attributable review waiver with reduced assurance"),
    _entry("fam.core.engineering-incident", ENGINEERING_CONTRACT_VERSION, EngineeringIncidentState, "Restart-safe diagnosis remediation recovery rollback and reporting lifecycle"),
    _entry("fam.core.engineering-incident-evidence", ENGINEERING_CONTRACT_VERSION, EngineeringIncidentEvidenceReceipt, "Typed evidence advancing one incident lifecycle stage"),
    _entry("fam.core.engineering-task-definition", ENGINEERING_CONTRACT_VERSION, EngineeringTaskDefinition, "Durable exact engineering task intent and acceptance policy"),
    _entry("fam.core.engineering-preparation", ENGINEERING_CONTRACT_VERSION, EngineeringPreparationResult, "Durable repository analysis architecture and candidate preparation"),
    _entry("fam.core.candidate-edit", ENGINEERING_CONTRACT_VERSION, CandidateEditRecord, "Intent-before-effect authorized candidate edit receipt"),
    _entry("fam.core.candidate-verification", ENGINEERING_CONTRACT_VERSION, CandidateVerificationRecord, "Intent-before-effect signed candidate verification receipt"),
    _entry("fam.core.candidate-changeset", ENGINEERING_CONTRACT_VERSION, CandidateChangesetRecord, "Owner-approved journaled candidate transaction record"),
    _entry("fam.core.candidate-generation-context", ENGINEERING_CONTRACT_VERSION, CandidateGenerationContext, "Bounded digest-bound candidate source context"),
    _entry("fam.core.generated-candidate-plan", ENGINEERING_CONTRACT_VERSION, GeneratedCandidatePlan, "Strict untrusted model candidate change proposal"),
    _entry("fam.core.candidate-generation-record", ENGINEERING_CONTRACT_VERSION, CandidateGenerationRecord, "Restart-safe pre-effect model generation record"),
    _entry("fam.core.engineering-tool-receipt", ENGINEERING_CONTRACT_VERSION, EngineeringToolReceipt, "Complete sandboxed tool execution receipt"),
    _entry("fam.core.language-tool-qualification", ENGINEERING_CONTRACT_VERSION, LanguageToolQualification, "Positive and negative language tool qualification"),
    _entry("fam.core.polyglot-recipe-matrix", ENGINEERING_CONTRACT_VERSION, PolyglotRecipeMatrix, "Complete signed polyglot recipe matrix"),
    _entry("fam.core.dependency-resolution-request", ENGINEERING_CONTRACT_VERSION, DependencyResolutionRequest, "Approved isolated dependency resolution request"),
    _entry("fam.core.dependency-resolution-receipt", ENGINEERING_CONTRACT_VERSION, DependencyResolutionReceipt, "Dependency SBOM and supply-chain receipt"),
    _entry("fam.core.host-administration-change-set", ENGINEERING_CONTRACT_VERSION, HostAdministrationChangeSet, "Owner-authenticated host administration changeset"),
    _entry("fam.core.host-administration-receipt", ENGINEERING_CONTRACT_VERSION, HostAdministrationReceipt, "Privileged broker host evidence receipt"),
    _entry("fam.core.secret-use-authorization", ENGINEERING_CONTRACT_VERSION, SecretUseAuthorization, "Tiered exact secret-use authorization"),
    _entry("fam.core.secret-use-receipt", ENGINEERING_CONTRACT_VERSION, SecretUseReceipt, "Redaction-safe secret use receipt"),
    _entry("fam.core.design-brief", ENGINEERING_CONTRACT_VERSION, DesignBrief, "Architecture-traceable design system brief"),
    _entry("fam.core.design-asset-record", ENGINEERING_CONTRACT_VERSION, DesignAssetRecord, "Provenance-bound sanitized creative asset"),
    _entry("fam.core.design-verification", ENGINEERING_CONTRACT_VERSION, DesignVerificationReceipt, "Accessibility visual and human-preview evidence"),
    _entry("fam.core.git-observation", ENGINEERING_CONTRACT_VERSION, GitRepositoryObservation, "Read-only repository status history refs remotes and diff"),
    _entry("fam.core.git-local-action", ENGINEERING_CONTRACT_VERSION, GitLocalAction, "Exact-path local branch stage commit or restore action"),
    _entry("fam.core.git-local-receipt", ENGINEERING_CONTRACT_VERSION, GitLocalActionReceipt, "Local Git action receipt"),
    _entry("fam.core.git-local-delivery", ENGINEERING_CONTRACT_VERSION, LocalGitDeliveryRecord, "Restart-safe approved changeset local Git delivery"),
    _entry("fam.core.git-publication-approval", ENGINEERING_CONTRACT_VERSION, GitPublicationApproval, "Final one-use remote publication approval"),
    _entry("fam.core.git-publication-local-state", ENGINEERING_CONTRACT_VERSION, GitPublicationLocalState, "Secret-free exact local state for publication"),
    _entry("fam.core.git-publication-proposal", ENGINEERING_CONTRACT_VERSION, GitPublicationProposal, "Exact separately grantable publication proposal"),
    _entry("fam.core.git-publication-receipt", ENGINEERING_CONTRACT_VERSION, GitPublicationReceipt, "Provider-neutral remote publication receipt"),
    _entry("fam.core.git-remote-ref-observation-request", ENGINEERING_CONTRACT_VERSION, GitRemoteRefObservationRequest, "Credential-opaque exact remote-ref observation request"),
    _entry("fam.core.git-remote-ref-observation", ENGINEERING_CONTRACT_VERSION, GitRemoteRefObservation, "Provider-attested exact remote-ref observation"),
    _entry("fam.core.engineering-loop-state", ENGINEERING_CONTRACT_VERSION, EngineeringLoopState, "Persistent bounded master engineering lifecycle"),
    _entry("fam.core.engineering-security-review", ENGINEERING_CONTRACT_VERSION, EngineeringSecurityReview, "Independent signed engineering security review"),
    _entry("fam.core.engineering-pressure-soak", ENGINEERING_CONTRACT_VERSION, EngineeringPressureSoakReport, "Minimum 24-hour mixed engineering pressure soak"),
    _entry("fam.core.installed-engineering-qualification", ENGINEERING_CONTRACT_VERSION, InstalledEngineeringQualification, "Fail-closed signed installed engineering exit evidence"),
    _entry("fam.routing.request", ROUTING_CONTRACT_VERSION, RoutingRequest, "Routing request"),
    _entry("fam.routing.result", ROUTING_CONTRACT_VERSION, RoutingResult, "Routing result"),
    _entry("fam.application.identity", APPLICATION_CONTRACT_VERSION, ApplicationIdentity, "Application identity"),
    _entry("fam.application.instance", APPLICATION_CONTRACT_VERSION, ApplicationInstance, "Application instance"),
    _entry("fam.application.capability", APPLICATION_CONTRACT_VERSION, CapabilityDescriptor, "Application capability"),
    _entry("fam.application.registry-entry", APPLICATION_CONTRACT_VERSION, CapabilityRegistryEntry, "Capability registry entry"),
    _entry("fam.application.permission-grant", APPLICATION_CONTRACT_VERSION, PermissionGrant, "Application permission grant"),
    _entry("fam.application.observation-request", APPLICATION_CONTRACT_VERSION, ObservationRequest, "Application observation request"),
    _entry("fam.application.observation-result", APPLICATION_CONTRACT_VERSION, ObservationResult, "Application observation result"),
    _entry("fam.application.action-preparation", APPLICATION_CONTRACT_VERSION, ActionPreparationRequest, "Application action preparation"),
    _entry("fam.application.action-proposal", APPLICATION_CONTRACT_VERSION, ActionProposal, "Application action proposal"),
    _entry("fam.application.action-confirmation", APPLICATION_CONTRACT_VERSION, ActionConfirmation, "Application action confirmation"),
    _entry("fam.application.action-result", APPLICATION_CONTRACT_VERSION, ActionResult, "Application action result"),
    _entry("fam.application.action-audit-intent", APPLICATION_ACTION_AUDIT_VERSION, ApplicationActionAuditIntent, "Application action audit intent"),
    _entry("fam.application.action-audit-record", APPLICATION_ACTION_AUDIT_VERSION, ApplicationActionAuditRecord, "Application action audit record"),
    _entry("fam.application.connector-registration", APPLICATION_CONTRACT_VERSION, ConnectorRegistration, "Application connector registration"),
    _entry("fam.application.connector-event", APPLICATION_CONTRACT_VERSION, ConnectorEvent, "Application connector event"),
    _entry("fam.application.failure", APPLICATION_FAILURE_CONTRACT_VERSION, ApplicationFailure, "Application failure"),
    _entry("fam.hardware.host-inventory", HOST_INVENTORY_CONTRACT_VERSION, HostInventory, "Host inventory"),
    _entry("fam.hardware.effective-budget", EFFECTIVE_RESOURCE_BUDGET_CONTRACT_VERSION, EffectiveResourceBudget, "Effective resource budget"),
    _entry("fam.scheduler.live-resources", LIVE_RESOURCE_OBSERVATION_VERSION, SchedulerResourceObservation, "Live scheduler resource observation"),
    _entry("fam.scheduler.context-profile", CONTEXT_MEMORY_CONTRACT_VERSION, ContextMemoryModelProfile, "Context memory model profile"),
    _entry("fam.scheduler.context-reservation", CONTEXT_MEMORY_CONTRACT_VERSION, ContextMemoryReservation, "Context memory reservation"),
    _entry("fam.scheduler.context-estimate", CONTEXT_MEMORY_CONTRACT_VERSION, ContextMemoryEstimate, "Context memory estimate"),
    _entry("fam.scheduler.expert-residency", EXPERT_RESIDENCY_CONTRACT_VERSION, ExpertResidencyCatalog, "Expert residency catalog"),
    _entry("fam.scheduler.admission-request", ADMISSION_CONTRACT_VERSION, AdmissionRequest, "Scheduler admission request"),
    _entry("fam.scheduler.admission-decision", ADMISSION_CONTRACT_VERSION, AdmissionDecision, "Scheduler admission decision"),
    _entry("fam.scheduler.cpu-baseline", CPU_BASELINE_CONTRACT_VERSION, CpuOnlyBaselineReport, "Constrained CPU-only scheduler baseline"),
    _entry("fam.scheduler.gpu-placement-request", GPU_PLACEMENT_CONTRACT_VERSION, GpuPlacementRequest, "GPU split placement request"),
    _entry("fam.scheduler.gpu-placement-decision", GPU_PLACEMENT_CONTRACT_VERSION, GpuPlacementDecision, "GPU split placement decision"),
    _entry("fam.scheduler.gpu-placement-evidence", GPU_PLACEMENT_CONTRACT_VERSION, GpuPlacementEvidence, "Observed GPU split placement evidence"),
    _entry("fam.scheduler.gpu-placement-report", GPU_PLACEMENT_CONTRACT_VERSION, FullWorkstationGpuReport, "Full workstation GPU placement report"),
    _entry("fam.scheduler.storage-artifact", STORAGE_PAGING_CONTRACT_VERSION, ModelStorageArtifact, "SSD model storage artifact"),
    _entry("fam.scheduler.artifact-cache", STORAGE_PAGING_CONTRACT_VERSION, ArtifactCacheObservation, "Mmap artifact cache observation"),
    _entry("fam.scheduler.storage-paging-evidence", STORAGE_PAGING_CONTRACT_VERSION, StoragePagingEvidence, "SSD paging and load I/O evidence"),
    _entry("fam.scheduler.npu-investigation", NPU_INVESTIGATION_CONTRACT_VERSION, NpuInvestigationReport, "Intel NPU micro-expert investigation"),
    _entry("fam.scheduler.cache-telemetry", CACHE_POLICY_CONTRACT_VERSION, CacheTelemetrySnapshot, "Tier-separated cache telemetry"),
    _entry("fam.scheduler.cache-policy-request", CACHE_POLICY_CONTRACT_VERSION, CachePolicyRequest, "Cache retention policy request"),
    _entry("fam.scheduler.cache-policy-decision", CACHE_POLICY_CONTRACT_VERSION, CachePolicyDecision, "Cache retention policy decision"),
    _entry("fam.scheduler.policy-replay", POLICY_REPLAY_CONTRACT_VERSION, SchedulerPolicyReplayReport, "Offline scheduler policy replay report"),
    _entry("fam.scheduler.prefetch-prediction-request", PREFETCH_CONTRACT_VERSION, PrefetchPredictionRequest, "Bounded prefetch prediction request"),
    _entry("fam.scheduler.prefetch-prediction", PREFETCH_CONTRACT_VERSION, PrefetchPrediction, "Historical transition prediction"),
    _entry("fam.scheduler.prefetch-policy-request", PREFETCH_CONTRACT_VERSION, PrefetchPolicyRequest, "Predictive prefetch admission request"),
    _entry("fam.scheduler.prefetch-policy-decision", PREFETCH_CONTRACT_VERSION, PrefetchPolicyDecision, "Predictive prefetch admission decision"),
    _entry("fam.scheduler.predictive-prefetch-report", PREFETCH_CONTRACT_VERSION, PredictivePrefetchReport, "Bounded predictive prefetch evidence"),
    _entry("fam.scheduler.expert-frequency-profile", EXPERT_FREQUENCY_CONTRACT_VERSION, ExpertFrequencyProfile, "Local expert frequency profile"),
    _entry("fam.configuration.scheduler-defaults", CONFIGURATION_CONTRACT_VERSION, SchedulerDefaults, "Scheduler safe defaults"),
    _entry("fam.configuration.validation-profile", CONFIGURATION_CONTRACT_VERSION, ValidationProfileConfiguration, "Named validation profile configuration"),
    _entry("fam.configuration.user-policy", CONFIGURATION_CONTRACT_VERSION, UserResourcePolicy, "User resource policy"),
    _entry("fam.configuration.session-override", CONFIGURATION_CONTRACT_VERSION, SessionResourceOverride, "Session resource override"),
    _entry("fam.configuration.discovered-state", CONFIGURATION_CONTRACT_VERSION, DiscoveredResourceState, "Discovered resource state"),
    _entry("fam.configuration.composition-request", CONFIGURATION_CONTRACT_VERSION, ConfigurationCompositionRequest, "Configuration composition request"),
    _entry("fam.configuration.composed-resources", CONFIGURATION_CONTRACT_VERSION, ComposedResourceConfiguration, "Composed resource configuration"),
    _entry("fam.configuration.validation-profile-document", VALIDATION_PROFILE_DOCUMENT_CONTRACT_VERSION, ValidationProfileDocument, "Validation profile document"),
    _entry(
        "fam.expert.manifest",
        LEGACY_EXPERT_MANIFEST_CONTRACT_VERSION,
        ExpertManifestV1Alpha1,
        "Legacy expert manifest",
    ),
    _entry(
        "fam.expert.compatibility-report",
        EXPERT_COMPATIBILITY_CONTRACT_VERSION,
        ExpertCompatibilityReport,
        "Expert compatibility report",
    ),
    _entry(
        "fam.expert.routing-embedding",
        EXPERT_ROUTING_METADATA_VERSION,
        ExpertRoutingEmbedding,
        "Expert semantic routing embedding",
    ),
    _entry(
        "fam.expert.benchmark-run",
        EXPERT_BENCHMARK_METADATA_VERSION,
        ExpertBenchmarkRun,
        "Expert benchmark run metadata",
    ),
    _entry(
        "fam.expert.runtime-binding",
        EXPERT_RUNTIME_BINDING_VERSION,
        ExpertRuntimeBinding,
        "Expert runtime artifact binding",
    ),
    _entry("fam.expert.mixed-benchmark-suite", MIXED_BENCHMARK_CONTRACT_VERSION, MixedBenchmarkSuite, "Mixed expert benchmark suite"),
    _entry("fam.expert.mixed-benchmark-report", MIXED_BENCHMARK_CONTRACT_VERSION, MixedBenchmarkReport, "Mixed expert benchmark report"),
    _entry("fam.expert.micro-advice", MICRO_EXPERT_CONTRACT_VERSION, MicroExpertAdvice, "Advisory micro-expert result"),
    _entry("fam.expert.micro-benchmark", MICRO_EXPERT_CONTRACT_VERSION, MicroExpertBenchmarkReport, "Micro-expert benchmark report"),
    _entry("fam.expert.escalation-trace", ESCALATION_TRACE_CONTRACT_VERSION, EscalationTraceReport, "Code escalation trace"),
    _entry("fam.expert.retrieval-result", RETRIEVAL_TIERS_CONTRACT_VERSION, VerifiedRetrievalResult, "Verified three-tier retrieval result"),
    _entry("fam.expert.retrieval-evidence", RETRIEVAL_EVIDENCE_CONTRACT_VERSION, RetrievalTierEvidence, "Three-tier retrieval evidence"),
    _entry("fam.expert.math-reasoning", MATH_EXPERT_CONTRACT_VERSION, MathReasoningAdvice, "Advisory mathematics reasoning"),
    _entry("fam.expert.math-solver-request", MATH_EXPERT_CONTRACT_VERSION, MathSolverRequest, "Deterministic mathematics solver request"),
    _entry("fam.expert.math-solver-result", MATH_EXPERT_CONTRACT_VERSION, MathSolverResult, "Deterministic mathematics solver result"),
    _entry("fam.expert.math-evidence", MATH_EVIDENCE_CONTRACT_VERSION, MathExpertEvidence, "Mathematics expert benchmark evidence"),
    _entry("fam.expert.media-evidence", MEDIA_EVIDENCE_CONTRACT_VERSION, MediaExpertEvidence, "Local media expert evidence"),
    _entry("fam.expert.efficiency-report", EFFICIENCY_REPORT_CONTRACT_VERSION, ExpertEfficiencyReport, "Measured expert efficiency report"),
    _entry("fam.expert.performance-slice", EXPERT_EVOLUTION_CONTRACT_VERSION, ExpertPerformanceSlice, "Expert performance evidence slice"),
    _entry("fam.expert.evolution-proposal", EXPERT_EVOLUTION_CONTRACT_VERSION, ExpertEvolutionProposal, "Advisory expert evolution proposal"),
    _entry("fam.expert.evolution-report", EXPERT_EVOLUTION_CONTRACT_VERSION, ExpertEvolutionReport, "Advisory expert evolution report"),
    _entry("fam.expert.phase9-exit", PHASE9_EXIT_CONTRACT_VERSION, Phase9ExitEvidence, "Phase 9 expert hierarchy exit evidence"),
    _entry(
        "fam.expert.manifest",
        EXPERT_MANIFEST_CONTRACT_VERSION,
        ExpertManifest,
        "Expert manifest",
        "v1alpha2",
    ),
    _entry("fam.verifier.manifest", VERIFIER_MANIFEST_CONTRACT_VERSION, VerifierManifest, "Verifier manifest"),
    _entry("fam.verifier.runtime-binding", VERIFIER_RUNTIME_BINDING_VERSION, VerifierRuntimeBinding, "Verifier runtime binding"),
    _entry("fam.verifier.trust-policy", VERIFIER_TRUST_POLICY_VERSION, VerifierTrustPolicy, "Verifier trust policy"),
    _entry("fam.verifier.activation-decision", VERIFIER_ACTIVATION_DECISION_VERSION, VerifierActivationDecision, "Verifier activation decision"),
    _entry(
        "fam.verifier.declaration", LEGACY_VERIFICATION_DECLARATION_VERSION,
        VerificationDeclarationV1Alpha1, "Legacy verifier acceptance declaration",
    ),
    _entry(
        "fam.verifier.declaration", VERIFICATION_DECLARATION_VERSION,
        VerificationDeclaration, "Query-bound verifier acceptance declaration", "v1alpha2",
    ),
    _entry("fam.verifier.run", VERIFICATION_RUN_VERSION, VerificationRunRecord, "Durable production verifier execution"),
    _entry("fam.verifier.media-report", MEDIA_VERIFICATION_VERSION, MediaArtifactTextReport, "Media artifact and text verification report"),
    _entry("fam.verifier.python-quality", PYTHON_QUALITY_CONTRACT_VERSION, PythonQualityReport, "Python quality verification report"),
    _entry("fam.verifier.language-quality", LANGUAGE_QUALITY_CONTRACT_VERSION, LanguageQualityReport, "Language quality verification report"),
    _entry("fam.verifier.math-request", MATH_VERIFICATION_CONTRACT_VERSION, MathVerificationRequest, "Math verification request"),
    _entry("fam.verifier.math-report", MATH_VERIFICATION_CONTRACT_VERSION, MathVerificationReport, "Math verification report"),
    _entry("fam.verifier.retrieval-report", RETRIEVAL_VERIFICATION_CONTRACT_VERSION, RetrievalVerificationReport, "Retrieval verification report"),
    _entry("fam.core.global-attempt-budget", GLOBAL_ATTEMPT_BUDGET_VERSION, GlobalAttemptBudget, "Global attempt budget"),
    _entry("fam.core.attempt-budget-reservation", GLOBAL_ATTEMPT_BUDGET_VERSION, AttemptBudgetReservation, "Attempt budget reservation"),
    _entry("fam.core.global-attempt-budget-snapshot", GLOBAL_ATTEMPT_BUDGET_VERSION, GlobalAttemptBudgetSnapshot, "Global attempt budget snapshot"),
    _entry("fam.connector.manifest", CONNECTOR_MANIFEST_CONTRACT_VERSION, ConnectorManifest, "Connector manifest"),
    _entry("fam.memory.record", MEMORY_RECORD_MANIFEST_CONTRACT_VERSION, MemoryRecordManifest, "Memory record manifest"),
    _entry("fam.memory.expiry-evaluation", MEMORY_LIFECYCLE_CONTRACT_VERSION, MemoryExpiryEvaluation, "Memory expiry evaluation"),
    _entry("fam.memory.deletion-request", MEMORY_LIFECYCLE_CONTRACT_VERSION, MemoryDeletionRequest, "Memory deletion request"),
    _entry("fam.memory.deletion-receipt", MEMORY_LIFECYCLE_CONTRACT_VERSION, MemoryDeletionReceipt, "Memory deletion receipt"),
    _entry("fam.memory.access-context", MEMORY_ACCESS_CONTRACT_VERSION, MemoryAccessContext, "Scoped memory access context"),
    _entry("fam.memory.document-approval", DOCUMENT_INDEX_CONTRACT_VERSION, DocumentIndexApproval, "Approved document index grant"),
    _entry("fam.memory.document-chunk", DOCUMENT_INDEX_CONTRACT_VERSION, IndexedDocumentChunk, "Embedded approved document chunk"),
    _entry("fam.memory.document-hit", DOCUMENT_INDEX_CONTRACT_VERSION, DocumentRetrievalHit, "Scoped document retrieval hit"),
    _entry("fam.memory.document-index-evidence", DOCUMENT_INDEX_CONTRACT_VERSION, DocumentIndexEvidence, "Approved document index evidence"),
    _entry("fam.memory.document-index-grant", DOCUMENT_INDEX_GRANT_VERSION, DocumentIndexGrant, "Explicit expiring document index grant"),
    _entry("fam.memory.document-index-receipt", DOCUMENT_INDEX_GRANT_VERSION, DocumentIndexReceipt, "Bounded document indexing receipt"),
    _entry("fam.memory.retrieval-candidate", MEMORY_RELEVANCE_CONTRACT_VERSION, MemoryRetrievalCandidate, "Scoped memory retrieval candidate"),
    _entry("fam.memory.relevance-decision", MEMORY_RELEVANCE_CONTRACT_VERSION, MemoryRelevanceDecision, "Memory relevance gate decision"),
    _entry("fam.memory.document-export", MEMORY_MANAGEMENT_CONTRACT_VERSION, MemoryDocumentExport, "Digest-verified memory document export"),
    _entry("fam.memory.document-inspection", MEMORY_MANAGEMENT_CONTRACT_VERSION, DocumentInspection, "Managed document inspection"),
    _entry("fam.memory.document-correction-request", MEMORY_MANAGEMENT_CONTRACT_VERSION, DocumentCorrectionRequest, "Confirmed document correction request"),
    _entry("fam.memory.document-expiration-request", MEMORY_MANAGEMENT_CONTRACT_VERSION, DocumentExpirationRequest, "Confirmed document expiration request"),
    _entry("fam.memory.document-deletion-request", MEMORY_MANAGEMENT_CONTRACT_VERSION, DocumentDeletionRequest, "Confirmed document deletion request"),
    _entry("fam.memory.document-management-receipt", MEMORY_MANAGEMENT_CONTRACT_VERSION, DocumentManagementReceipt, "Durable document management receipt"),
    _entry("fam.memory.management-evidence", MEMORY_MANAGEMENT_CONTRACT_VERSION, MemoryManagementEvidence, "Memory management lifecycle evidence"),
    _entry("fam.memory.encryption-evidence", MEMORY_ENCRYPTION_CONTRACT_VERSION, MemoryEncryptionEvidence, "Owner-isolated memory encryption evidence"),
    _entry("fam.memory.quality-privacy-report", MEMORY_QUALITY_CONTRACT_VERSION, MemoryQualityPrivacyReport, "Memory retrieval quality and privacy report"),
    _entry("fam.memory.phase10-exit", PHASE10_EXIT_CONTRACT_VERSION, Phase10ExitEvidence, "Phase 10 memory-fabric exit evidence"),
    _entry("fam.adaptation.verified-outcome", OUTCOME_PREDICTION_CONTRACT_VERSION, VerifiedOutcomeObservation, "Verified local workflow outcome"),
    _entry("fam.adaptation.workflow-prediction", OUTCOME_PREDICTION_CONTRACT_VERSION, WorkflowOutcomePrediction, "Local context and escalation prediction"),
    _entry("fam.adaptation.verified-learning", VERIFIED_LEARNING_CONTRACT_VERSION, VerifiedLearningOutcome, "Content-free verified production learning outcome"),
    _entry("fam.adaptation.live-snapshot", LIVE_ADAPTATION_CONTRACT_VERSION, LiveAdaptationSnapshot, "Content-free live adaptation snapshot"),
    _entry("fam.adaptation.prewarm-receipt", LIVE_ADAPTATION_CONTRACT_VERSION, ModelPrewarmReceipt, "Resource-bounded model prewarm receipt"),
    _entry("fam.adaptation.control-state", LIVE_ADAPTATION_CONTROL_VERSION, LiveAdaptationControlState, "Owner-visible live adaptation state"),
    _entry("fam.adaptation.control-request", LIVE_ADAPTATION_CONTROL_VERSION, LiveAdaptationControlRequest, "Confirmed live adaptation control request"),
    _entry("fam.adaptation.control-receipt", LIVE_ADAPTATION_CONTROL_VERSION, LiveAdaptationControlReceipt, "Durable live adaptation control receipt"),
    _entry("fam.adaptation.inference-observation", LIVE_ADAPTATION_CONTROL_VERSION, AdaptationInferenceObservation, "Content-free adaptation inference observation"),
    _entry("fam.adaptation.health-sample", LIVE_ADAPTATION_CONTROL_VERSION, AdaptationHealthSample, "Verified adaptation health sample"),
    _entry("fam.adaptation.health-summary", LIVE_ADAPTATION_CONTROL_VERSION, AdaptationHealthSummary, "Repeated adaptation health summary"),
    _entry("fam.adaptation.live-drift-report", LIVE_ADAPTATION_CONTROL_VERSION, LiveAdaptationDriftReport, "Quality thermal latency and policy drift report"),
    _entry("fam.adaptation.preference-profile", PREFERENCE_CONTRACT_VERSION, UserPreferenceProfile, "Inspectable user preference profile"),
    _entry("fam.adaptation.preference-reset", PREFERENCE_CONTRACT_VERSION, PreferenceResetReceipt, "User preference reset receipt"),
    _entry("fam.adaptation.operating-state", RESOURCE_ADAPTATION_CONTRACT_VERSION, OperatingState, "Observed battery thermal load and idle state"),
    _entry("fam.adaptation.operating-policy", RESOURCE_ADAPTATION_CONTRACT_VERSION, OperatingPolicyDecision, "Operating-state adaptation policy"),
    _entry("fam.adaptation.snapshot", ADAPTATION_DRIFT_CONTRACT_VERSION, AdaptationSnapshot, "Immutable adaptation snapshot"),
    _entry("fam.adaptation.drift-report", ADAPTATION_DRIFT_CONTRACT_VERSION, AdaptationDriftReport, "Adaptation drift report"),
    _entry("fam.adaptation.rollback-receipt", ADAPTATION_DRIFT_CONTRACT_VERSION, AdaptationRollbackReceipt, "Adaptation rollback receipt"),
    _entry("fam.adaptation.phase11-exit", PHASE11_EXIT_CONTRACT_VERSION, Phase11ExitEvidence, "Phase 11 repeated-workflow exit evidence"),
    _entry("fam.fabric.device-identity", DEVICE_IDENTITY_CONTRACT_VERSION, DeviceIdentity, "Cryptographic device identity"),
    _entry("fam.fabric.enrollment-request", DEVICE_IDENTITY_CONTRACT_VERSION, DeviceEnrollmentRequest, "Device enrollment request"),
    _entry("fam.fabric.enrollment-challenge", DEVICE_IDENTITY_CONTRACT_VERSION, DeviceEnrollmentChallenge, "Device proof-of-key challenge"),
    _entry("fam.fabric.enrollment-record", DEVICE_IDENTITY_CONTRACT_VERSION, DeviceEnrollmentRecord, "Owner-bound trusted device enrollment"),
    _entry("fam.fabric.peer-endpoint", DEVICE_PAIRING_CONTRACT_VERSION, PeerEndpoint, "Manually advertised peer endpoint"),
    _entry("fam.fabric.pairing-offer", DEVICE_PAIRING_CONTRACT_VERSION, DevicePairingOffer, "Signed expiring device pairing offer"),
    _entry("fam.fabric.pairing-approval", DEVICE_PAIRING_CONTRACT_VERSION, DevicePairingApproval, "Owner-confirmed signed peer approval"),
    _entry("fam.fabric.authenticated-peer", MUTUAL_TLS_CONTRACT_VERSION, AuthenticatedPeer, "Mutually authenticated TLS peer"),
    _entry("fam.fabric.peer-enrollment", PEER_ENROLLMENT_CONTRACT_VERSION, PeerEnrollmentRecord, "Durable owner-approved peer enrollment"),
    _entry("fam.fabric.peer-control-request", PEER_CONTROL_CONTRACT_VERSION, PeerControlRequest, "Authenticated peer health request"),
    _entry("fam.fabric.peer-control-response", PEER_CONTROL_CONTRACT_VERSION, PeerControlResponse, "Authenticated peer health response"),
    _entry("fam.fabric.peer-service-configuration", PEER_SERVICE_CONFIGURATION_VERSION, PeerServiceConfiguration, "Installed peer listener configuration"),
    _entry("fam.fabric.peer-capability", PEER_STATE_CONTRACT_VERSION, PeerCapabilityDeclaration, "Peer-signed expert capability declaration"),
    _entry("fam.fabric.peer-performance", PEER_STATE_CONTRACT_VERSION, PeerPerformanceObservation, "Locally measured authenticated peer performance"),
    _entry("fam.fabric.peer-privacy-record", PEER_STATE_CONTRACT_VERSION, PeerPrivacyPolicyRecord, "Revisioned per-peer privacy policy"),
    _entry("fam.fabric.peer-management-request", PEER_STATE_CONTRACT_VERSION, PeerManagementRequest, "Confirmed peer control request"),
    _entry("fam.fabric.peer-management-receipt", PEER_STATE_CONTRACT_VERSION, PeerManagementReceipt, "Durable local peer control receipt"),
    _entry("fam.fabric.trusted-peer-directory", TRUSTED_PEER_DIRECTORY_VERSION, TrustedPeerDirectoryEntry, "Active trusted peer directory entry"),
    _entry("fam.fabric.remote-task-descriptor", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteTaskDescriptor, "Content-free remote task descriptor"),
    _entry("fam.fabric.remote-context-fragment", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteRawContextFragment, "Explicit remote raw context fragment"),
    _entry("fam.fabric.minimum-context", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteContextEnvelope, "Signed exact-byte minimum remote context"),
    _entry("fam.fabric.context-receipt", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteContextReceipt, "Peer-signed remote context receipt"),
    _entry("fam.fabric.context-send-request", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteContextSendRequest, "Local authorized remote context request"),
    _entry("fam.fabric.context-disclosure-evidence", REMOTE_CONTEXT_CONTRACT_VERSION, RemoteContextDisclosureEvidence, "Encrypted content-free disclosure evidence"),
    _entry("fam.fabric.remote-execution-authority", REMOTE_EXECUTION_CONTRACT_VERSION, RemoteExecutionAuthority, "Explicit confirmed remote execution authority"),
    _entry("fam.fabric.remote-execution-plan", REMOTE_EXECUTION_CONTRACT_VERSION, RemoteExecutionPlan, "Content-free Core remote execution route"),
    _entry("fam.fabric.remote-execution-request", REMOTE_EXECUTION_CONTRACT_VERSION, RemoteExecutionRequest, "Signed bounded remote inference request"),
    _entry("fam.fabric.remote-execution-result", REMOTE_EXECUTION_CONTRACT_VERSION, RemoteExecutionResult, "Peer-signed complete remote inference result"),
    _entry("fam.fabric.remote-execution-evidence", REMOTE_EXECUTION_EVIDENCE_VERSION, RemoteExecutionEvidence, "Content-free durable complete remote inference evidence"),
    _entry("fam.fabric.remote-recovery-evidence", REMOTE_RECOVERY_EVIDENCE_VERSION, RemoteRecoveryEvidence, "Content-free remote disconnect reconciliation evidence"),
    _entry("fam.fabric.physical-host-evidence", PHYSICAL_HOST_EVIDENCE_VERSION, PhysicalHostEvidence, "Content-free physical Linux host qualification evidence"),
    _entry("fam.fabric.physical-peer-observation", PHYSICAL_PEER_OBSERVATION_VERSION, PhysicalPeerObservation, "Device-signed content-free physical peer checkpoint"),
    _entry("fam.fabric.remote-capability", REMOTE_PRIVACY_CONTRACT_VERSION, RemoteExpertCapability, "Remote expert capability"),
    _entry("fam.fabric.remote-privacy-policy", REMOTE_PRIVACY_CONTRACT_VERSION, RemotePrivacyPolicy, "Remote context privacy policy"),
    _entry("fam.fabric.remote-context-request", REMOTE_PRIVACY_CONTRACT_VERSION, RemoteContextRequest, "Remote context request"),
    _entry("fam.fabric.remote-privacy-decision", REMOTE_PRIVACY_CONTRACT_VERSION, RemotePrivacyDecision, "Remote privacy decision"),
    _entry("fam.fabric.handshake", FABRIC_TRANSPORT_CONTRACT_VERSION, FabricHandshake, "Signed fabric handshake"),
    _entry("fam.fabric.encrypted-envelope", FABRIC_TRANSPORT_CONTRACT_VERSION, FabricEncryptedEnvelope, "Authenticated encrypted fabric envelope"),
    _entry("fam.fabric.route-candidate", FABRIC_SCHEDULING_CONTRACT_VERSION, FabricRouteCandidate, "Local or remote fabric route candidate"),
    _entry("fam.fabric.route-decision", FABRIC_SCHEDULING_CONTRACT_VERSION, FabricRouteDecision, "Latency-aware fabric route decision"),
    _entry("fam.fabric.recovery-decision", FABRIC_RECOVERY_CONTRACT_VERSION, FabricRecoveryDecision, "Remote failure recovery decision"),
    _entry("fam.fabric.multidevice-demo", FABRIC_DEMO_CONTRACT_VERSION, MultiDeviceDemoReport, "Trusted three-device fabric demonstration"),
    _entry("fam.factory.failure-trace", EXPERT_DISCOVERY_CONTRACT_VERSION, FailureTrace, "Verified expert failure trace"),
    _entry("fam.factory.failure-cluster", EXPERT_DISCOVERY_CONTRACT_VERSION, FailureTraceCluster, "Clustered expert failures"),
    _entry("fam.factory.missing-capability", EXPERT_DISCOVERY_CONTRACT_VERSION, MissingCapabilityProposal, "Missing capability proposal"),
    _entry("fam.factory.verified-failure-trace", FACTORY_FAILURE_DISCOVERY_VERSION, VerifiedFailureTrace, "Signed content-free production failure trace"),
    _entry("fam.factory.verified-failure-cluster", FACTORY_FAILURE_DISCOVERY_VERSION, VerifiedFailureCluster, "Immutable production failure cluster"),
    _entry("fam.factory.capability-proposal", FACTORY_FAILURE_DISCOVERY_VERSION, FactoryCapabilityProposal, "Proposal-only factory capability discovery"),
    _entry("fam.factory.dataset-split-policy", FACTORY_DATASET_PROVENANCE_VERSION, DatasetSplitPolicy, "Deterministic split-before-synthesis policy"),
    _entry("fam.factory.training-capture-grant", FACTORY_DATASET_PROVENANCE_VERSION, TrainingCaptureGrant, "Confirmed expiring training-content capture grant"),
    _entry("fam.factory.training-capture-revocation", FACTORY_DATASET_PROVENANCE_VERSION, TrainingCaptureRevocation, "Revision-bound capture revocation receipt"),
    _entry("fam.factory.captured-dataset-source", FACTORY_DATASET_PROVENANCE_VERSION, CapturedDatasetSource, "Encrypted provenance-bound dataset source"),
    _entry("fam.factory.synthetic-example-proposal", FACTORY_DATASET_PROVENANCE_VERSION, SyntheticExampleProposal, "Unreviewed provenance-bound synthetic example"),
    _entry("fam.factory.synthetic-example-review", FACTORY_DATASET_PROVENANCE_VERSION, SyntheticExampleReview, "Independent synthetic example review"),
    _entry("fam.factory.sealed-dataset-partition", FACTORY_SEALED_DATASET_VERSION, SealedDatasetPartition, "Immutable content-bound dataset partition"),
    _entry("fam.factory.sealed-dataset-blob-receipt", FACTORY_SEALED_DATASET_VERSION, SealedDatasetBlobReceipt, "Encrypted immutable partition blob receipt"),
    _entry("fam.factory.dataset-leakage-finding", FACTORY_SEALED_DATASET_VERSION, DatasetLeakageFinding, "Blocking cross-partition leakage finding"),
    _entry("fam.factory.dataset-leakage-report", FACTORY_SEALED_DATASET_VERSION, DatasetLeakageReport, "Immutable exact and near-duplicate leakage evidence"),
    _entry("fam.factory.sealed-dataset", FACTORY_SEALED_DATASET_VERSION, SealedFactoryDataset, "Immutable training-ready dataset manifest"),
    _entry("fam.factory.approved-base-model", FACTORY_TRAINING_APPROVAL_VERSION, ApprovedBaseModel, "Immutable approved training base and tokenizer"),
    _entry("fam.factory.adapter-training-recipe", FACTORY_TRAINING_APPROVAL_VERSION, AdapterTrainingRecipe, "Bounded LoRA or QLoRA training recipe"),
    _entry("fam.factory.training-resource-budget", FACTORY_TRAINING_APPROVAL_VERSION, TrainingResourceBudget, "Explicit training resource budget"),
    _entry("fam.factory.training-approval", FACTORY_TRAINING_APPROVAL_VERSION, FactoryTrainingApproval, "Confirmed one-use training authority"),
    _entry("fam.factory.training-approval-consumption", FACTORY_TRAINING_APPROVAL_VERSION, TrainingApprovalConsumption, "Durable one-use training authority consumption"),
    _entry("fam.factory.training-approval-revocation", FACTORY_TRAINING_APPROVAL_VERSION, TrainingApprovalRevocation, "Revision-bound training authority revocation"),
    _entry("fam.factory.training-backend-environment", FACTORY_TRAINING_BACKEND_VERSION, TrainingBackendEnvironment, "Probed pinned CUDA training environment"),
    _entry("fam.factory.adapter-training-job", FACTORY_TRAINING_BACKEND_VERSION, AdapterTrainingJob, "Consumed one-use isolated adapter training job"),
    _entry("fam.factory.training-terminal-receipt", FACTORY_TRAINING_BACKEND_VERSION, TrainingTerminalReceipt, "Immutable isolated training terminal evidence"),
    _entry("fam.factory.training-resource-snapshot", FACTORY_RESOURCE_ADMISSION_VERSION, TrainingResourceSnapshot, "Live CPU RAM disk and GPU admission evidence"),
    _entry("fam.factory.training-admission-decision", FACTORY_RESOURCE_ADMISSION_VERSION, TrainingAdmissionDecision, "Fail-closed safe training admission decision"),
    _entry("fam.factory.evaluation-policy", FACTORY_EVALUATION_VERSION, FactoryEvaluationPolicy, "Immutable specialist promotion policy"),
    _entry("fam.factory.evaluation-approval", FACTORY_EVALUATION_VERSION, FactoryEvaluationApproval, "Confirmed one-use held-out evaluation authority"),
    _entry("fam.factory.held-out-access-receipt", FACTORY_EVALUATION_VERSION, HeldOutAccessReceipt, "Content-free held-out plaintext disposal receipt"),
    _entry("fam.factory.paired-evaluation-measurement", FACTORY_EVALUATION_VERSION, PairedEvaluationMeasurement, "Candidate and incumbent paired measurement"),
    _entry("fam.factory.expert-evaluation-report", FACTORY_EVALUATION_VERSION, ExpertEvaluationReport, "Immutable held-out and hardware comparison report"),
    _entry("fam.factory.expert-comparison-decision", FACTORY_EVALUATION_VERSION, ExpertComparisonDecision, "Fail-closed expert promotion decision"),
    _entry("fam.factory.conversion-environment", FACTORY_CONVERSION_VERSION, FactoryConversionEnvironment, "Pinned llama.cpp conversion environment"),
    _entry("fam.factory.conversion-approval", FACTORY_CONVERSION_VERSION, FactoryConversionApproval, "One-use promotable adapter conversion authority"),
    _entry("fam.factory.conversion-receipt", FACTORY_CONVERSION_VERSION, FactoryConversionReceipt, "Immutable network-denied GGUF conversion evidence"),
    _entry("fam.factory.specialist-release-lineage", FACTORY_SPECIALIST_RELEASE_VERSION, FactorySpecialistReleaseLineage, "Digest-bound promoted specialist lineage"),
    _entry("fam.factory.specialist-package-receipt", FACTORY_SPECIALIST_RELEASE_VERSION, FactorySpecialistPackageReceipt, "Signed disabled specialist package installation"),
    _entry("fam.factory.canary-approval", FACTORY_CANARY_VERSION, FactoryCanaryApproval, "One-use specialist canary authority"),
    _entry("fam.factory.canary-report", FACTORY_CANARY_VERSION, FactoryCanaryReport, "Verifier and scheduler specialist canary evidence"),
    _entry("fam.factory.activation-decision", FACTORY_CANARY_VERSION, FactoryActivationDecision, "Separately signed specialist activation decision"),
    _entry("fam.factory.specialist-lifecycle-request", FACTORY_SPECIALIST_LIFECYCLE_VERSION, FactorySpecialistLifecycleRequest, "Durable confirmed rollback or retirement authority"),
    _entry("fam.factory.specialist-lifecycle-receipt", FACTORY_SPECIALIST_LIFECYCLE_VERSION, FactorySpecialistLifecycleReceipt, "Audit-preserving rollback or retirement result"),
    _entry("fam.factory.teacher-dataset", FACTORY_PIPELINE_CONTRACT_VERSION, TeacherDataset, "Teacher dataset"),
    _entry("fam.factory.distillation-plan", FACTORY_PIPELINE_CONTRACT_VERSION, DistillationPlan, "Distillation plan"),
    _entry("fam.factory.adapter-plan", FACTORY_PIPELINE_CONTRACT_VERSION, AdapterTrainingPlan, "Adapter training plan"),
    _entry("fam.factory.evaluation-plan", FACTORY_PIPELINE_CONTRACT_VERSION, EvaluationPlan, "Expert evaluation plan"),
    _entry("fam.factory.trained-micro-expert", FACTORY_TRAINING_CONTRACT_VERSION, TrainedMicroExpert, "Trained local micro-expert"),
    _entry("fam.factory.hardware-metrics", FACTORY_OBJECTIVE_CONTRACT_VERSION, HardwareTrainingMetrics, "Hardware-aware training metrics"),
    _entry("fam.factory.quantized-variant", FACTORY_QUANTIZATION_CONTRACT_VERSION, QuantizedVariant, "Calibrated quantized expert variant"),
    _entry("fam.factory.published-package", FACTORY_RELEASE_CONTRACT_VERSION, PublishedExpertPackage, "Signed published expert package"),
    _entry("fam.factory.regression-gate", FACTORY_REGRESSION_CONTRACT_VERSION, RegressionGateResult, "Continuous expert regression gate"),
    _entry("fam.factory.lifecycle-report", FACTORY_LIFECYCLE_CONTRACT_VERSION, FactoryLifecycleReport, "End-to-end Expert Factory lifecycle"),
    _entry("fam.product.security-review", "fam.product.security-review/v1alpha1", SecurityReviewReport, "Release security review"),
    _entry("fam.product.update-receipt", UPDATE_CONTRACT_VERSION, UpdateReceipt, "Atomic release update receipt"),
    _entry("fam.product.release-manifest", UPDATE_CONTRACT_VERSION, SignedReleaseManifest, "Signed complete release manifest"),
    _entry("fam.product.recovery-decision", RECOVERY_CONTRACT_VERSION, RecoveryDecision, "Recovery-mode decision"),
    _entry("fam.product.persisted-action", RESTART_RECOVERY_VERSION, PersistedActionRecord, "Persisted application action state"),
    _entry("fam.product.restart-decision", RESTART_RECOVERY_VERSION, RestartRecoveryDecision, "Restart action recovery decision"),
    _entry("fam.product.request-recovery", REQUEST_RECOVERY_VERSION, RequestRecoveryRecord, "Persisted request recovery classification"),
    _entry("fam.product.request-restart-decision", REQUEST_RECOVERY_VERSION, RequestRestartDecision, "Request restart decision"),
    _entry("fam.product.worker-budget-policy", WORKER_BUDGET_VERSION, WorkerBudgetPolicy, "Production worker budget policy"),
    _entry("fam.product.worker-limit-plan", WORKER_BUDGET_VERSION, WorkerLimitPlan, "Derived production worker limits"),
    _entry("fam.product.soak-report", SOAK_CONTRACT_VERSION, SoakReport, "Production soak report"),
    _entry("fam.product.installation-receipt", INSTALL_CONTRACT_VERSION, InstallationReceipt, "Linux installation receipt"),
    _entry("fam.console.snapshot", CONSOLE_CONTRACT_VERSION, ConsoleSnapshot, "FAM Console snapshot"),
    _entry("fam.product.benchmark-publication", BENCHMARK_PUBLICATION_VERSION, BenchmarkPublication, "Reference benchmark publication"),
    _entry("fam.product.phase14-exit", PHASE14_EXIT_VERSION, Phase14ExitEvidence, "Phase 14 product exit evidence"),
    _entry("fam.product.phase15-exit", PHASE15_EXIT_VERSION, Phase15ExitEvidence, "Installed operational exit evidence"),
    _entry(
        "fam.product.integration-coverage",
        INTEGRATION_COVERAGE_VERSION,
        IntegrationCoverageManifest,
        "Final integration coverage manifest",
    ),
    _entry("fam.core.runtime-model", INFERENCE_EXECUTION_VERSION, RuntimeModelEntry, "Installed runtime model evidence"),
    _entry("fam.core.runtime-selection", INFERENCE_EXECUTION_VERSION, RuntimeModelSelection, "Resource-aware runtime selection"),
    _entry("fam.core.inference-execution", INFERENCE_EXECUTION_VERSION, InferenceExecutionRecord, "Restart-safe inference execution"),
    _entry("fam.core.application-execution", APPLICATION_EXECUTION_VERSION, ApplicationExecutionRecord, "Restart-safe application execution"),
    _entry("fam.registry.package-signature", REGISTRY_TRUST_CONTRACT_VERSION, PackageSignature, "Detached package signature"),
    _entry("fam.registry.trust-policy", REGISTRY_TRUST_CONTRACT_VERSION, PackageTrustPolicy, "Package trust policy"),
    _entry("fam.registry.validation-report", REGISTRY_TRUST_CONTRACT_VERSION, PackageValidationReport, "Package validation report"),
    _entry("fam.registry.installation-state", PACKAGE_LIFECYCLE_CONTRACT_VERSION, ExpertPackageInstallationState, "Expert package installation state"),
    _entry("fam.failure.envelope", FAILURE_CONTRACT_VERSION, FailureEnvelope, "FAM failure envelope"),
    _entry("fam.failure.degradation", FAILURE_CONTRACT_VERSION, DegradationNotice, "FAM degradation notice"),
    _entry("fam.shell.ask", SHELL_CONTRACT_VERSION, ShellAskCommand, "FAM Shell ask command"),
    _entry("fam.shell.verified-ask", SHELL_CONTRACT_VERSION, ShellVerifiedAskCommand, "FAM Shell verified ask command"),
    _entry("fam.shell.snapshot-query", SHELL_CONTRACT_VERSION, ShellSnapshotQuery, "FAM Shell snapshot query"),
    _entry("fam.shell.decision", SHELL_CONTRACT_VERSION, ShellDecisionCommand, "FAM Shell decision command"),
    _entry("fam.shell.cancel", SHELL_CONTRACT_VERSION, ShellCancelCommand, "FAM Shell cancellation command"),
    _entry(
        "fam.shell.snapshot", LEGACY_SHELL_SNAPSHOT_VERSION,
        ShellSessionSnapshotV1Alpha1, "FAM Shell session snapshot",
    ),
    _entry(
        "fam.shell.snapshot", SHELL_SNAPSHOT_CONTRACT_VERSION,
        ShellSessionSnapshot, "Typed FAM Shell session snapshot", "v1alpha2",
    ),
    _entry("fam.shell.memory-query", SHELL_MEMORY_CONTRACT_VERSION, ShellMemoryQuery, "Bounded Shell memory query"),
    _entry("fam.shell.memory-response", SHELL_MEMORY_CONTRACT_VERSION, ShellMemoryResponse, "Bounded Shell memory response"),
    _entry("fam.shell.adaptation-query", SHELL_ADAPTATION_CONTRACT_VERSION, ShellAdaptationQuery, "Bounded Shell adaptation query"),
    _entry("fam.shell.adaptation-response", SHELL_ADAPTATION_CONTRACT_VERSION, ShellAdaptationResponse, "Bounded Shell adaptation response"),
    _entry("fam.shell.peer-query", SHELL_PEER_CONTRACT_VERSION, ShellPeerQuery, "Bounded Shell trusted peer query"),
    _entry("fam.shell.peer-probe", SHELL_PEER_CONTRACT_VERSION, ShellPeerProbeRequest, "Authenticated Shell peer probe request"),
    _entry("fam.shell.peer-response", SHELL_PEER_CONTRACT_VERSION, ShellPeerResponse, "Bounded Shell trusted peer response"),
    _entry("fam.shell.engineering-context", SHELL_ENGINEERING_AUTHORITY_VERSION, ShellEngineeringContextRequest, "Session-bound owner engineering authentication context request"),
    _entry("fam.shell.engineering-activation", SHELL_ENGINEERING_AUTHORITY_VERSION, ShellEngineeringActivationRequest, "Exact owner engineering grant activation request"),
    _entry("fam.shell.engineering-query", SHELL_ENGINEERING_AUTHORITY_VERSION, ShellEngineeringGrantQuery, "Owner engineering grant or audit query"),
    _entry("fam.shell.engineering-revocation", SHELL_ENGINEERING_AUTHORITY_VERSION, ShellEngineeringRevocationRequest, "Confirmed owner engineering grant revocation"),
    _entry("fam.shell.engineering-response", SHELL_ENGINEERING_AUTHORITY_VERSION, ShellEngineeringAuthorityResponse, "Bounded owner engineering authority response"),
    _entry("fam.shell.integration-environment-start", SHELL_INTEGRATION_ENVIRONMENT_VERSION, ShellIntegrationEnvironmentStartRequest, "Confirmed persistent integration environment start"),
    _entry("fam.shell.integration-environment-query", SHELL_INTEGRATION_ENVIRONMENT_VERSION, ShellIntegrationEnvironmentQuery, "Owner integration environment query"),
    _entry("fam.shell.integration-environment-control", SHELL_INTEGRATION_ENVIRONMENT_VERSION, ShellIntegrationEnvironmentControlRequest, "Confirmed integration cleanup or reconciliation"),
    _entry("fam.shell.integration-environment-response", SHELL_INTEGRATION_ENVIRONMENT_VERSION, ShellIntegrationEnvironmentResponse, "Typed integration environment lifecycle response"),
    _entry("fam.shell.engineering-secret-query", SHELL_ENGINEERING_SECRET_VERSION, ShellEngineeringSecretQuery, "Metadata-only owner engineering secret query"),
    _entry("fam.shell.engineering-secret-mutation", SHELL_ENGINEERING_SECRET_VERSION, ShellEngineeringSecretMutation, "Confirmed owner engineering secret mutation"),
    _entry("fam.shell.engineering-secret-response", SHELL_ENGINEERING_SECRET_VERSION, ShellEngineeringSecretResponse, "Metadata-only engineering secret response"),
    _entry("fam.shell.engineering-loop-start", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringLoopStartRequest, "Confirmed persistent engineering lifecycle start"),
    _entry("fam.shell.engineering-loop-query", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringLoopQuery, "Owner engineering lifecycle query"),
    _entry("fam.shell.engineering-loop-mutation", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringLoopMutation, "Confirmed engineering lifecycle transition"),
    _entry("fam.shell.engineering-loop-response", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringLoopResponse, "Persistent engineering lifecycle projection"),
    _entry("fam.shell.engineering-candidate-edit", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringCandidateEditRequest, "Confirmed bounded candidate edit with transient content"),
    _entry("fam.shell.engineering-candidate-verification", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringCandidateVerificationRequest, "Confirmed signed candidate verification request"),
    _entry("fam.shell.engineering-candidate-reverification", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringCandidateReverificationRequest, "Confirmed independent post-apply verification request"),
    _entry("fam.shell.engineering-changeset-preview", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringChangesetPreviewRequest, "Confirmed candidate changeset preview request"),
    _entry("fam.shell.engineering-changeset-apply", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringChangesetApplyRequest, "Exact owner-approved candidate changeset apply request"),
    _entry("fam.shell.engineering-publication", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringPublicationRequest, "Exact separately granted Git publication request"),
    _entry("fam.shell.engineering-incident-advance", SHELL_ENGINEERING_LOOP_VERSION, ShellEngineeringIncidentAdvanceRequest, "Confirmed evidence-bound engineering incident transition"),
)

# Strict JSON configuration documents are parsed into policy objects rather than
# encoded as dataclass wire envelopes, so their hand-authored schemas are tracked
# separately from serialized contract roots.
STATIC_CONFIGURATION_SCHEMAS = (
    "v1alpha1/fam.product.fallbacks-config.schema.json",
    "v1alpha1/fam.product.mcp-ingress-config.schema.json",
)

_BY_SCHEMA_ID = {entry.schema_id: entry for entry in SCHEMA_DESCRIPTORS}
_BY_ROOT_TYPE = {entry.root_type: entry for entry in SCHEMA_DESCRIPTORS}
_KNOWN_FAMILIES = {entry.family_id for entry in SCHEMA_DESCRIPTORS}


def descriptor_for_schema(schema_id: str) -> SchemaDescriptor | None:
    return _BY_SCHEMA_ID.get(schema_id)


def descriptor_for_type(root_type: type[object]) -> SchemaDescriptor | None:
    return _BY_ROOT_TYPE.get(root_type)


def family_is_known(family_id: str) -> bool:
    return family_id in _KNOWN_FAMILIES
