"""Evidence-driven local Expert Factory."""

from fam_os.expert_factory.discovery import (
    EXPERT_DISCOVERY_CONTRACT_VERSION, FailureTrace, FailureTraceCluster,
    MissingCapabilityProposal, cluster_failures,
)
from fam_os.expert_factory.pipeline import (
    FACTORY_PIPELINE_CONTRACT_VERSION, AdapterTrainingPlan, DistillationPlan,
    EvaluationPlan, TeacherDataset,
)
from fam_os.expert_factory.training import (
    FACTORY_TRAINING_CONTRACT_VERSION, LabeledExample, TokenWeight,
    TrainedMicroExpert, train_micro_expert,
)
from fam_os.expert_factory.objective import (
    FACTORY_OBJECTIVE_CONTRACT_VERSION, HardwareObjectiveWeights,
    HardwareTrainingMetrics, hardware_objective,
)
from fam_os.expert_factory.quantization import FACTORY_QUANTIZATION_CONTRACT_VERSION, QuantizedVariant
from fam_os.expert_factory.release import FACTORY_RELEASE_CONTRACT_VERSION, PublishedExpertPackage
from fam_os.expert_factory.regression import FACTORY_REGRESSION_CONTRACT_VERSION, RegressionGateResult
from fam_os.expert_factory.lifecycle import FACTORY_LIFECYCLE_CONTRACT_VERSION, FactoryLifecycleReport
from fam_os.expert_factory.failure_discovery import (
    FACTORY_FAILURE_DISCOVERY_VERSION,
    FactoryCapabilityProposal,
    VerifiedFailureCluster,
    VerifiedFailureTrace,
    build_verified_failure_trace,
    discover_failure_clusters,
    failure_family_id,
)
from fam_os.expert_factory.dataset_provenance import (
    FACTORY_DATASET_PROVENANCE_VERSION,
    CapturedDatasetSource,
    DatasetPartition,
    DatasetSplitPolicy,
    ExampleReviewKind,
    HeldOutEvaluationKind,
    HeldOutVerifierKind,
    SyntheticExampleProposal,
    SyntheticExampleReview,
    TrainingCaptureGrant,
    TrainingCaptureRevocation,
    TrainingDataSensitivity,
    TrainingSourceKind,
    build_captured_source,
    build_synthetic_example,
)
from fam_os.expert_factory.training_approval import (
    FACTORY_TRAINING_APPROVAL_VERSION,
    AdapterTrainingMethod,
    AdapterTrainingRecipe,
    ApprovedBaseModel,
    FactoryTrainingApproval,
    TrainingApprovalConsumption,
    TrainingApprovalRevocation,
    TrainingComputeDtype,
    TrainingResourceBudget,
)
from fam_os.expert_factory.dataset_sealing import (
    FACTORY_SEALED_DATASET_VERSION,
    DatasetLeakageFinding,
    DatasetLeakageKind,
    DatasetLeakageReport,
    SealedDatasetPartition,
    SealedDatasetBlobReceipt,
    SealedFactoryDataset,
    canonical_partition_bytes,
    build_sealed_dataset_blob_receipt,
    leakage_report_digest,
    seal_factory_dataset,
    sealed_dataset_digest,
    sealed_dataset_blob_digest,
)
from fam_os.expert_factory.training_backend import (
    FACTORY_TRAINING_BACKEND_VERSION,
    AdapterTrainingJob,
    TrainingBackendEnvironment,
    TrainingTerminalReceipt,
    TrainingTerminalStatus,
    build_training_environment,
    build_training_job,
    build_training_terminal_receipt,
    training_environment_digest,
    training_job_digest,
    training_terminal_receipt_digest,
)
from fam_os.expert_factory.training_ports import TrainingBackend
from fam_os.expert_factory.resource_admission import (
    FACTORY_RESOURCE_ADMISSION_VERSION,
    TrainingAdmissionDecision,
    TrainingResourceSnapshot,
    admission_decision_digest,
    build_resource_snapshot,
    decide_training_admission,
    resource_snapshot_digest,
)
from fam_os.expert_factory.evaluation import (
    FACTORY_EVALUATION_VERSION,
    EvaluationCaseKind,
    ExpertComparisonDecision,
    ExpertEvaluationReport,
    FactoryEvaluationApproval,
    FactoryEvaluationPolicy,
    HeldOutAccessReceipt,
    PairedEvaluationMeasurement,
    build_evaluation_approval,
    build_evaluation_policy,
    build_evaluation_report,
    build_held_out_access_receipt,
    build_paired_measurement,
    comparison_decision_digest,
    decide_comparison,
    evaluation_approval_digest,
    evaluation_policy_digest,
    evaluation_report_digest,
    held_out_access_digest,
    paired_measurement_digest,
)
from fam_os.expert_factory.conversion import (
    FACTORY_CONVERSION_VERSION,
    ConversionOutputType,
    ConversionStatus,
    FactoryConversionApproval,
    FactoryConversionEnvironment,
    FactoryConversionReceipt,
    build_conversion_approval,
    build_conversion_environment,
    build_conversion_receipt,
    conversion_approval_digest,
    conversion_environment_digest,
    conversion_receipt_digest,
)
from fam_os.expert_factory.specialist_release import (
    FACTORY_SPECIALIST_RELEASE_VERSION,
    FactorySpecialistPackageReceipt,
    FactorySpecialistReleaseLineage,
    build_specialist_package_receipt,
    build_specialist_release_lineage,
)
from fam_os.expert_factory.canary import (
    FACTORY_CANARY_VERSION,
    FactoryActivationDecision,
    FactoryCanaryApproval,
    FactoryCanaryReport,
    FactoryCanaryStatus,
    build_canary_approval,
    build_canary_report,
    decide_canary_activation,
)
from fam_os.expert_factory.specialist_lifecycle import (
    FACTORY_SPECIALIST_LIFECYCLE_VERSION,
    FactorySpecialistLifecycleAction,
    FactorySpecialistLifecycleReceipt,
    FactorySpecialistLifecycleRequest,
    build_specialist_lifecycle_receipt,
    build_specialist_lifecycle_request,
    specialist_lifecycle_receipt_digest,
    specialist_lifecycle_request_digest,
)

__all__ = [
    "EXPERT_DISCOVERY_CONTRACT_VERSION", "FailureTrace", "FailureTraceCluster",
    "MissingCapabilityProposal", "cluster_failures",
    "FACTORY_PIPELINE_CONTRACT_VERSION", "AdapterTrainingPlan", "DistillationPlan",
    "EvaluationPlan", "TeacherDataset", "FACTORY_TRAINING_CONTRACT_VERSION",
    "LabeledExample", "TokenWeight", "TrainedMicroExpert", "train_micro_expert",
    "FACTORY_OBJECTIVE_CONTRACT_VERSION", "HardwareObjectiveWeights",
    "HardwareTrainingMetrics", "hardware_objective", "FACTORY_QUANTIZATION_CONTRACT_VERSION",
    "QuantizedVariant", "FACTORY_RELEASE_CONTRACT_VERSION", "PublishedExpertPackage",
    "FACTORY_REGRESSION_CONTRACT_VERSION", "RegressionGateResult",
    "FACTORY_LIFECYCLE_CONTRACT_VERSION", "FactoryLifecycleReport",
    "FACTORY_FAILURE_DISCOVERY_VERSION", "FactoryCapabilityProposal",
    "VerifiedFailureCluster", "VerifiedFailureTrace",
    "build_verified_failure_trace", "discover_failure_clusters",
    "failure_family_id",
    "FACTORY_DATASET_PROVENANCE_VERSION", "CapturedDatasetSource",
    "DatasetPartition", "DatasetSplitPolicy", "ExampleReviewKind",
    "HeldOutEvaluationKind", "HeldOutVerifierKind",
    "SyntheticExampleProposal", "SyntheticExampleReview",
    "TrainingCaptureGrant", "TrainingCaptureRevocation",
    "TrainingDataSensitivity", "TrainingSourceKind", "build_captured_source",
    "build_synthetic_example",
    "FACTORY_TRAINING_APPROVAL_VERSION", "AdapterTrainingMethod",
    "AdapterTrainingRecipe", "ApprovedBaseModel", "FactoryTrainingApproval",
    "TrainingApprovalConsumption", "TrainingApprovalRevocation",
    "TrainingComputeDtype", "TrainingResourceBudget",
    "FACTORY_SEALED_DATASET_VERSION", "DatasetLeakageFinding",
    "DatasetLeakageKind", "DatasetLeakageReport", "SealedDatasetPartition",
    "SealedDatasetBlobReceipt",
    "SealedFactoryDataset", "leakage_report_digest", "seal_factory_dataset",
    "sealed_dataset_digest", "sealed_dataset_blob_digest",
    "canonical_partition_bytes", "build_sealed_dataset_blob_receipt",
    "FACTORY_TRAINING_BACKEND_VERSION", "AdapterTrainingJob",
    "TrainingBackendEnvironment", "TrainingTerminalReceipt",
    "TrainingTerminalStatus", "build_training_environment",
    "build_training_job", "build_training_terminal_receipt",
    "training_environment_digest",
    "training_job_digest", "training_terminal_receipt_digest", "TrainingBackend",
    "FACTORY_RESOURCE_ADMISSION_VERSION", "TrainingAdmissionDecision",
    "TrainingResourceSnapshot", "admission_decision_digest",
    "build_resource_snapshot", "decide_training_admission",
    "resource_snapshot_digest",
    "FACTORY_EVALUATION_VERSION", "EvaluationCaseKind",
    "ExpertComparisonDecision", "ExpertEvaluationReport",
    "FactoryEvaluationApproval", "FactoryEvaluationPolicy",
    "HeldOutAccessReceipt", "PairedEvaluationMeasurement",
    "build_evaluation_approval", "build_evaluation_policy",
    "build_evaluation_report", "build_held_out_access_receipt",
    "build_paired_measurement", "comparison_decision_digest",
    "decide_comparison", "evaluation_approval_digest",
    "evaluation_policy_digest", "evaluation_report_digest",
    "held_out_access_digest", "paired_measurement_digest",
    "FACTORY_CONVERSION_VERSION", "ConversionOutputType", "ConversionStatus",
    "FactoryConversionApproval", "FactoryConversionEnvironment",
    "FactoryConversionReceipt", "build_conversion_approval",
    "build_conversion_environment", "build_conversion_receipt",
    "conversion_approval_digest", "conversion_environment_digest",
    "conversion_receipt_digest",
    "FACTORY_SPECIALIST_RELEASE_VERSION", "FactorySpecialistPackageReceipt",
    "FactorySpecialistReleaseLineage", "build_specialist_package_receipt",
    "build_specialist_release_lineage",
    "FACTORY_CANARY_VERSION", "FactoryActivationDecision",
    "FactoryCanaryApproval", "FactoryCanaryReport", "FactoryCanaryStatus",
    "build_canary_approval", "build_canary_report",
    "decide_canary_activation",
    "FACTORY_SPECIALIST_LIFECYCLE_VERSION",
    "FactorySpecialistLifecycleAction", "FactorySpecialistLifecycleReceipt",
    "FactorySpecialistLifecycleRequest", "build_specialist_lifecycle_receipt",
    "build_specialist_lifecycle_request",
    "specialist_lifecycle_receipt_digest",
    "specialist_lifecycle_request_digest",
]
